In [1]:
###This notebook has the purpose of merging different datasets using 'concat'

In [2]:
import pandas as pd

df_mfn1 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_mfn_applied_duty_23_02_2026_16_16_01.csv")
df_mfn1

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,961590,A000,World,7.375000,WTO IDB
1,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,961100,A000,World,2.700000,WTO IDB
2,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,960110,A000,World,0.000000,WTO IDB
3,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,950730,A000,World,5.880000,WTO IDB
4,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,950699,A000,World,1.871429,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
21994,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,30229,A000,World,0.000000,WTO IDB
21995,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,30219,A000,World,0.000000,WTO IDB
21996,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,20641,A000,World,0.000000,WTO IDB
21997,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,10632,A000,World,1.800000,WTO IDB
21998,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,10130,A000,World,6.800000,WTO IDB

In [3]:
df_mfn2 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_mfn_applied_duty_23_02_2026_16_17_25.csv")
df_mfn2

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,960899,A000,World,3.522500,WTO IDB
1,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,960891,A000,World,0.000000,WTO IDB
2,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,950822,A000,World,0.000000,WTO IDB
3,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,940521,A000,World,4.533333,WTO IDB
4,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,940320,A000,World,0.000000,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
11219,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,20725,A000,World,11.655000,WTO IDB
11220,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,20329,A000,World,0.215000,WTO IDB
11221,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10612,A000,World,0.000000,WTO IDB
11222,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10221,A000,World,0.000000,WTO IDB
11223,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10130,A000,World,6.800000,WTO IDB

In [4]:
df_mfn = pd.concat([df_mfn1,df_mfn2])
df_mfn

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,961590,A000,World,7.375000,WTO IDB
1,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,961100,A000,World,2.700000,WTO IDB
2,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,960110,A000,World,0.000000,WTO IDB
3,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,950730,A000,World,5.880000,WTO IDB
4,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,950699,A000,World,1.871429,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
11219,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,20725,A000,World,11.655000,WTO IDB
11220,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,20329,A000,World,0.215000,WTO IDB
11221,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10612,A000,World,0.000000,WTO IDB
11222,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10221,A000,World,0.000000,WTO IDB
11223,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,10130,A000,World,6.800000,WTO IDB

In [5]:
df_mfn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33223 entries, 0 to 11223
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   indicator               33223 non-null  object
 1   reporter_code           33223 non-null  object
 2   reporter_name           33223 non-null  object
 3   year                    33223 non-null  int64
 4   classification_version  33223 non-null  object
 5   product_code            33223 non-null  int64
 6   partner_code            33223 non-null  object
 7   partner_name            33223 non-null  object
 8   value                   33133 non-null  float64
 9   source                  33223 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 2.8+ MB

In [6]:
df_mfn.product_code.value_counts()

product_code
20442     6
20742     6
20990     6
21020     6
30232     6
         ..
854140    2
293138    2
290339    2
293131    2
999999    1
Name: count, Length: 5758, dtype: int64

In [7]:
df_mfn[df_mfn["product_code"]==20442]

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
5386,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2020,HS17,20442,A000,World,0.295,WTO IDB
7201,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2021,HS17,20442,A000,World,0.245,WTO IDB
13091,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2022,HS22,20442,A000,World,0.245,WTO IDB
17929,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2023,HS22,20442,A000,World,0.355,WTO IDB
3069,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2024,HS22,20442,A000,World,0.395,WTO IDB
6961,MFN_applied_duty_simple_average_in_percentage,C840,United States of America,2025,HS22,20442,A000,World,0.325,WTO IDB

In [8]:
#df_mfn.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Merged Datasets\merged_mfn.csv")

In [24]:
df_imports1 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_imports_02_03_2026_13_06_16.csv")
df_imports1

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Imports,C840,United States of America,2024,HS22,848690,C344,"Hong Kong, China",3.797400e+05,WTO IDB
1,Imports,C840,United States of America,2024,HS22,848520,C376,Israel,1.930075e+07,WTO IDB
2,Imports,C840,United States of America,2024,HS22,853710,C156,China,1.206776e+09,WTO IDB
3,Imports,C840,United States of America,2024,HS22,640610,C392,Japan,6.489000e+03,WTO IDB
4,Imports,C840,United States of America,2024,HS22,620462,C032,Argentina,9.175000e+03,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
443928,Imports,C840,United States of America,2022,HS22,970390,C807,North Macedonia,1.541500e+04,WTO IDB
443929,Imports,C840,United States of America,2022,HS22,970390,C784,United Arab Emirates,6.694410e+05,WTO IDB
443930,Imports,C840,United States of America,2022,HS22,970390,C591,Panama,3.595800e+04,WTO IDB
443931,Imports,C840,United States of America,2022,HS22,970390,C702,Singapore,1.440622e+06,WTO IDB
443932,Imports,C840,United States of America,2022,HS22,970310,A000,World,1.016708e+08,WTO IDB

In [29]:
df_imports1 = df_imports1[df_imports1["partner_name"]!="World"]

In [34]:
df_imports1.pivot_table(index="partner_name",columns="year",values="value", aggfunc="sum")/1000000

year,2020,2021,2022,2024
partner_name,,,,
Afghanistan,15.222749,21.338501,22.381071,21.822318
Albania,45.681878,63.819962,141.652886,127.050726
Algeria,421.753170,1744.598545,2933.187075,2685.660208
Andorra,5.372439,8.006603,9.585350,3.294031
Angola,479.235749,1024.533542,1516.739077,1662.167957
...,...,...,...,...
"Venezuela, Bolivarian Republic of",189.656450,285.514088,668.289886,5668.317352
Viet Nam,77826.637107,100531.442922,123504.555376,139497.409343
Yemen,3.768829,10.151168,18.253561,8.732058
Zambia,53.777420,180.374920,135.380660,174.090103
Zimbabwe,36.709598,42.180016,86.104961,65.888540

In [30]:
round(df_imports1.groupby("year")["value"].agg("sum")/1000000,2)

year
2020    2227485.83
2021    2696464.32
2022    3105319.01
2024    3123563.02
Name: value, dtype: float64

In [ ]:
#df_imports2 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_imports_23_02_2026_16_17_46.csv")
#df_imports2

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Imports,C840,United States of America,2024,HS22,970690,C152,Chile,235000.0,WTO IDB
1,Imports,C840,United States of America,2024,HS22,970610,C051,Armenia,2732.0,WTO IDB
2,Imports,C840,United States of America,2024,HS22,970539,C702,Singapore,754625.0,WTO IDB
3,Imports,C840,United States of America,2024,HS22,970539,C032,Argentina,24401.0,WTO IDB
4,Imports,C840,United States of America,2024,HS22,970522,U918,European Union,957813.0,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
113299,Imports,C840,United States of America,2024,HS22,30235,A000,World,137289204.0,WTO IDB
113300,Imports,C840,United States of America,2024,HS22,30119,C036,Australia,359607.0,WTO IDB
113301,Imports,C840,United States of America,2024,HS22,30111,C768,Togo,78078.0,WTO IDB
113302,Imports,C840,United States of America,2024,HS22,20690,C036,Australia,14101425.0,WTO IDB
113303,Imports,C840,United States of America,2024,HS22,10121,C076,Brazil,2075753.0,WTO IDB

In [11]:
df_imports = pd.concat([df_imports1,df_imports2])
df_imports

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Imports,C840,United States of America,2020,HS17,960190,C332,Haiti,2822.0,WTO IDB
1,Imports,C840,United States of America,2020,HS17,950720,C484,Mexico,351695.0,WTO IDB
2,Imports,C840,United States of America,2020,HS17,950691,C188,Costa Rica,8140.0,WTO IDB
3,Imports,C840,United States of America,2020,HS17,950662,C344,"Hong Kong, China",20535.0,WTO IDB
4,Imports,C840,United States of America,2020,HS17,950619,C104,Myanmar,4098.0,WTO IDB
...,...,...,...,...,...,...,...,...,...,...
113299,Imports,C840,United States of America,2024,HS22,30235,A000,World,137289204.0,WTO IDB
113300,Imports,C840,United States of America,2024,HS22,30119,C036,Australia,359607.0,WTO IDB
113301,Imports,C840,United States of America,2024,HS22,30111,C768,Togo,78078.0,WTO IDB
113302,Imports,C840,United States of America,2024,HS22,20690,C036,Australia,14101425.0,WTO IDB
113303,Imports,C840,United States of America,2024,HS22,10121,C076,Brazil,2075753.0,WTO IDB

In [12]:
df_imports.info()

<class 'pandas.core.frame.DataFrame'>
Index: 557111 entries, 0 to 113303
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   indicator               557111 non-null  object
 1   reporter_code           557111 non-null  object
 2   reporter_name           557111 non-null  object
 3   year                    557111 non-null  int64
 4   classification_version  557111 non-null  object
 5   product_code            557111 non-null  int64
 6   partner_code            557111 non-null  object
 7   partner_name            557111 non-null  object
 8   value                   557111 non-null  float64
 9   source                  557111 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 46.8+ MB

In [23]:
df_imports[(df_imports["partner_name"] == "Canada")&(df_imports["year"] == 2024)].value.sum()

np.float64(392463885760.7016)

In [14]:
#df_imports.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Merged Datasets\merged_imports.csv")

In [15]:
df_exports1 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_exports_23_02_2026_16_16_57.csv")
df_exports1

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Exports,C840,United States of America,2021,HS17,10649,C756,Switzerland,8855,UN Comtrade
1,Exports,C840,United States of America,2021,HS17,20430,C662,Saint Lucia,6011,UN Comtrade
2,Exports,C840,United States of America,2021,HS17,20622,C320,Guatemala,416126,UN Comtrade
3,Exports,C840,United States of America,2021,HS17,20714,C417,Kyrgyz Republic,95238,UN Comtrade
4,Exports,C840,United States of America,2021,HS17,21012,C591,Panama,2200023,UN Comtrade
...,...,...,...,...,...,...,...,...,...,...
874313,Exports,C840,United States of America,2020,HS17,841480,C892,Serbia,37635,UN Comtrade
874314,Exports,C840,United States of America,2020,HS17,841480,U918,European Union,323061067,UN Comtrade
874315,Exports,C840,United States of America,2020,HS17,841490,C052,Barbados,1259921,UN Comtrade
874316,Exports,C840,United States of America,2020,HS17,841490,C446,"Macao, China",15119,UN Comtrade
874317,Exports,C840,United States of America,2020,HS17,841490,C860,Uzbekistan,269650,UN Comtrade

In [16]:
df_exports2 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\adb_exports_23_02_2026_16_18_08.csv")
df_exports2

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Exports,C840,United States of America,2024,HS22,999999,C064,Bhutan,302202,UN Comtrade
1,Exports,C840,United States of America,2024,HS22,970690,C328,Guyana,5000,UN Comtrade
2,Exports,C840,United States of America,2024,HS22,970529,C076,Brazil,6970,UN Comtrade
3,Exports,C840,United States of America,2024,HS22,961590,C702,Singapore,7194,UN Comtrade
4,Exports,C840,United States of America,2024,HS22,961400,C484,Mexico,1012237,UN Comtrade
...,...,...,...,...,...,...,...,...,...,...
220113,Exports,C840,United States of America,2024,HS22,392210,C740,Suriname,15352,UN Comtrade
220114,Exports,C840,United States of America,2024,HS22,392190,C398,Kazakhstan,209249,UN Comtrade
220115,Exports,C840,United States of America,2024,HS22,392112,C170,Colombia,136041,UN Comtrade
220116,Exports,C840,United States of America,2024,HS22,392099,C458,Malaysia,7418329,UN Comtrade
220117,Exports,C840,United States of America,2024,HS22,392073,C320,Guatemala,2783,UN Comtrade

In [17]:
df_exports = pd.concat([df_exports1,df_exports2])
df_exports

,indicator,reporter_code,reporter_name,year,classification_version,product_code,partner_code,partner_name,value,source
0,Exports,C840,United States of America,2021,HS17,10649,C756,Switzerland,8855,UN Comtrade
1,Exports,C840,United States of America,2021,HS17,20430,C662,Saint Lucia,6011,UN Comtrade
2,Exports,C840,United States of America,2021,HS17,20622,C320,Guatemala,416126,UN Comtrade
3,Exports,C840,United States of America,2021,HS17,20714,C417,Kyrgyz Republic,95238,UN Comtrade
4,Exports,C840,United States of America,2021,HS17,21012,C591,Panama,2200023,UN Comtrade
...,...,...,...,...,...,...,...,...,...,...
220113,Exports,C840,United States of America,2024,HS22,392210,C740,Suriname,15352,UN Comtrade
220114,Exports,C840,United States of America,2024,HS22,392190,C398,Kazakhstan,209249,UN Comtrade
220115,Exports,C840,United States of America,2024,HS22,392112,C170,Colombia,136041,UN Comtrade
220116,Exports,C840,United States of America,2024,HS22,392099,C458,Malaysia,7418329,UN Comtrade
220117,Exports,C840,United States of America,2024,HS22,392073,C320,Guatemala,2783,UN Comtrade

In [18]:
df_exports.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1094436 entries, 0 to 220117
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   indicator               1094436 non-null  object
 1   reporter_code           1094436 non-null  object
 2   reporter_name           1094436 non-null  object
 3   year                    1094436 non-null  int64
 4   classification_version  1094436 non-null  object
 5   product_code            1094436 non-null  int64
 6   partner_code            1094436 non-null  object
 7   partner_name            1094436 non-null  object
 8   value                   1094436 non-null  int64
 9   source                  1094436 non-null  object
dtypes: int64(3), object(7)
memory usage: 91.8+ MB

In [19]:
#df_exports.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Merged Datasets\merged_exports.csv")