In [2]:
import pandas as pd

In [3]:
currency = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\CurrencyTable.xlsx")
currency.head(5)

  observation_date  EXCAUS  EXCHUS   EXMXUS  EXUSEU
0       2023-01-01  1.3422  6.7904  18.9705  1.0777
1       2023-02-01  1.3454  6.8380  18.6368  1.0702
2       2023-03-01  1.3683  6.8909  18.3892  1.0711
3       2023-04-01  1.3484  6.8876  18.0948  1.0962
4       2023-05-01  1.3517  6.9854  17.7489  1.0867

In [4]:
currency.rename(columns={"EXCAUS":"CAD_USD",
                         "EXCHUS":"CNY_USD",
                         "EXMXUS":"MXN_USD",
                         "EXUSEU":"EUR_USD"},inplace=True)

In [5]:
currency["Month"] = currency["observation_date"].dt.month

In [6]:
currency["Year"] = currency["observation_date"].dt.year

In [7]:
def q(row):
    if row["Month"] in (1,2,3):
        return "Q1"
    elif row["Month"] in (4,5,6):
        return "Q2"
    elif row["Month"] in (7,8,9):
        return "Q3"
    elif row["Month"] in (10,11,12):
        return "Q4"
    else:
        return "Error!"

In [8]:
currency["Quarter"] = currency.apply(q,axis=1)
currency.head(5)

  observation_date  CAD_USD  CNY_USD  MXN_USD  EUR_USD  Month  Year Quarter
0       2023-01-01   1.3422   6.7904  18.9705   1.0777      1  2023      Q1
1       2023-02-01   1.3454   6.8380  18.6368   1.0702      2  2023      Q1
2       2023-03-01   1.3683   6.8909  18.3892   1.0711      3  2023      Q1
3       2023-04-01   1.3484   6.8876  18.0948   1.0962      4  2023      Q2
4       2023-05-01   1.3517   6.9854  17.7489   1.0867      5  2023      Q2

In [9]:
CAD_USD_table = currency.pivot_table(index=["Year","Quarter"],values="CAD_USD",aggfunc="mean").reset_index()
CAD_USD_table.rename(columns={"CAD_USD":"Value"},inplace=True)
CAD_USD_table["Country"] = "Canada"
CAD_USD_table["Index"] = "Currency"
CAD_USD_table["Unit"] = "CAD_USD"
CAD_USD_table

    Year Quarter     Value Country     Index     Unit
0   2023      Q1  1.351967  Canada  Currency  CAD_USD
1   2023      Q2  1.342900  Canada  Currency  CAD_USD
2   2023      Q3  1.340667  Canada  Currency  CAD_USD
3   2023      Q4  1.361167  Canada  Currency  CAD_USD
4   2024      Q1  1.348633  Canada  Currency  CAD_USD
5   2024      Q2  1.368200  Canada  Currency  CAD_USD
6   2024      Q3  1.363833  Canada  Currency  CAD_USD
7   2024      Q4  1.399233  Canada  Currency  CAD_USD
8   2025      Q1  1.434800  Canada  Currency  CAD_USD
9   2025      Q2  1.383867  Canada  Currency  CAD_USD
10  2025      Q3  1.377400  Canada  Currency  CAD_USD
11  2025      Q4  1.394633  Canada  Currency  CAD_USD

In [10]:
CNY_USD_table = currency.pivot_table(index=["Year","Quarter"],values="CNY_USD",aggfunc="mean").reset_index()
CNY_USD_table.rename(columns={"CNY_USD":"Value"},inplace=True)
CNY_USD_table["Country"] = "China"
CNY_USD_table["Index"] = "Currency"
CNY_USD_table["Unit"] = "CNY_USD"
CNY_USD_table

    Year Quarter     Value Country     Index     Unit
0   2023      Q1  6.839767   China  Currency  CNY_USD
1   2023      Q2  7.011467   China  Currency  CNY_USD
2   2023      Q3  7.244267   China  Currency  CNY_USD
3   2023      Q4  7.223300   China  Currency  CNY_USD
4   2024      Q1  7.188567   China  Currency  CNY_USD
5   2024      Q2  7.241600   China  Currency  CNY_USD
6   2024      Q3  7.161467   China  Currency  CNY_USD
7   2024      Q4  7.191700   China  Currency  CNY_USD
8   2025      Q1  7.272800   China  Currency  CNY_USD
9   2025      Q2  7.231267   China  Currency  CNY_USD
10  2025      Q3  7.156767   China  Currency  CNY_USD
11  2025      Q4  7.090033   China  Currency  CNY_USD

In [11]:
MXN_USD_table = currency.pivot_table(index=["Year","Quarter"],values="MXN_USD",aggfunc="mean").reset_index()
MXN_USD_table.rename(columns={"MXN_USD":"Value"},inplace=True)
MXN_USD_table["Country"] = "Mexico"
MXN_USD_table["Index"] = "Currency"
MXN_USD_table["Unit"] = "MXN_USD"
MXN_USD_table

    Year Quarter      Value Country     Index     Unit
0   2023      Q1  18.665500  Mexico  Currency  MXN_USD
1   2023      Q2  17.694800  Mexico  Currency  MXN_USD
2   2023      Q3  17.058767  Mexico  Currency  MXN_USD
3   2023      Q4  17.537000  Mexico  Currency  MXN_USD
4   2024      Q1  16.985400  Mexico  Currency  MXN_USD
5   2024      Q2  17.266233  Mexico  Currency  MXN_USD
6   2024      Q3  18.944900  Mexico  Currency  MXN_USD
7   2024      Q4  20.106000  Mexico  Currency  MXN_USD
8   2025      Q1  20.411000  Mexico  Currency  MXN_USD
9   2025      Q2  19.505433  Mexico  Currency  MXN_USD
10  2025      Q3  18.624600  Mexico  Currency  MXN_USD
11  2025      Q4  18.304900  Mexico  Currency  MXN_USD

In [12]:
EUR_USD_table = currency.pivot_table(index=["Year","Quarter"],values="EUR_USD",aggfunc="mean").reset_index()
EUR_USD_table.rename(columns={"EUR_USD":"Value"},inplace=True)
EUR_USD_table["Country"] = "European Union"
EUR_USD_table["Index"] = "Currency"
EUR_USD_table["Unit"] = "EUR_USD"
EUR_USD_table

    Year Quarter     Value         Country     Index     Unit
0   2023      Q1  1.073000  European Union  Currency  EUR_USD
1   2023      Q2  1.088967  European Union  Currency  EUR_USD
2   2023      Q3  1.088300  European Union  Currency  EUR_USD
3   2023      Q4  1.076433  European Union  Currency  EUR_USD
4   2024      Q1  1.085400  European Union  Currency  EUR_USD
5   2024      Q2  1.076567  European Union  Currency  EUR_USD
6   2024      Q3  1.099033  European Union  Currency  EUR_USD
7   2024      Q4  1.066267  European Union  Currency  EUR_USD
8   2025      Q1  1.052733  European Union  Currency  EUR_USD
9   2025      Q2  1.134667  European Union  Currency  EUR_USD
10  2025      Q3  1.168567  European Union  Currency  EUR_USD
11  2025      Q4  1.163633  European Union  Currency  EUR_USD

In [13]:
index_table = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\index table.xlsx")
index_table = index_table[["Year","Quarter","Country","Index","Value","Unit"]]
index_table.head(5)

   Year Quarter        Country Index    Value         Unit
0  2023      Q1  United States   GDP  6769600  USD million
1  2023      Q2  United States   GDP  6915600  USD million
2  2023      Q3  United States   GDP  7046700  USD million
3  2023      Q4  United States   GDP  7187500  USD million
4  2024      Q1  United States   GDP  7029200  USD million

In [14]:
index_table2 = pd.concat([index_table, CAD_USD_table, CNY_USD_table, MXN_USD_table, EUR_USD_table])
index_table2

    Year Quarter         Country     Index     Value         Unit
0   2023      Q1   United States       GDP   6769600  USD million
1   2023      Q2   United States       GDP   6915600  USD million
2   2023      Q3   United States       GDP   7046700  USD million
3   2023      Q4   United States       GDP   7187500  USD million
4   2024      Q1   United States       GDP   7029200  USD million
..   ...     ...             ...       ...       ...          ...
7   2024      Q4  European Union  Currency  1.066267      EUR_USD
8   2025      Q1  European Union  Currency  1.052733      EUR_USD
9   2025      Q2  European Union  Currency  1.134667      EUR_USD
10  2025      Q3  European Union  Currency  1.168567      EUR_USD
11  2025      Q4  European Union  Currency  1.163633      EUR_USD

[107 rows x 6 columns]

In [15]:
#index_table2.to_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\index table v2.xlsx")

In [25]:
MTS = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\MTS.csv")
MTS = MTS[["Record Date","Current Month Receipt or Outlay Amount","Calendar Year","Calendar Month Number"]]
MTS["Current Month Receipt or Outlay Amount"] = MTS["Current Month Receipt or Outlay Amount"]/1000000
MTS

,Record Date,Current Month Receipt or Outlay Amount,Calendar Year,Calendar Month Number
0,2025-12-31,27892.382035,2025,12
1,2025-11-30,30755.952020,2025,11
2,2025-10-31,31353.501081,2025,10
3,2025-09-30,29674.953322,2025,9
4,2025-08-31,29502.942750,2025,8
5,2025-07-31,27670.054031,2025,7
6,2025-06-30,26631.664232,2025,6
7,2025-05-31,22172.564539,2025,5
8,2025-04-30,15633.917349,2025,4
9,2025-03-31,8167.908460,2025,3
10,2025-02-28,7246.812675,2025,2
11,2025-01-31,7341.415937,2025,1
12,2024-12-31,6814.380564,2024,12
13,2024-11-30,6711.869038,2024,11
14,2024-10-31,7297.256976,2024,10
15,2024-09-30,7249.259468,2024,9
16,2024-08-31,7046.951549,2024,8
17,2024-07-31,7133.488191,2024,7
18,2024-06-30,6323.344669,2024,6
19,2024-05-31,5224.661702,2024,5
20,2024-04-30,6366.508728,2024,4
21,2024-03-31,6064.284894,2024,3
22,2024-02-29,6208.388231,2024,2
23,2024-01-31,6476.625976,2024,1
24,2023-12-31,5744.452855,2023,12
25,2023-11-30,6296.206194,2023,11
26,2023-10-31,6902.737489,2023,10
27,2023-09-30,6678.440109,2023,9
28,2023-08-31,6325.140881,2023,8
29,2023-07-31,6909.949194,2023,7
30,2023-06-30,6475.488283,2023,6
31,2023-05-31,6373.091749,2023,5
32,2023-04-30,6349.693067,2023,4
33,2023-03-31,6151.606563,2023,3
34,2023-02-28,6349.062417,2023,2
35,2023-01-31,6837.686961,2023,1

In [ ]:
#MTS.to_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\MTS v2.xlsx")