In [127]:
import pandas as pd

df_exports = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\Exports_2020_2024_HS2.csv" , encoding="latin1")
df_exports

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,A,20200101,2020,52,2020,842,USA,USA,X,Export,...,True,0,False,0.0,29282,29282,4,False,True,NaN
C,A,20200101,2020,52,2020,842,USA,USA,X,Export,...,True,0,False,0.0,1098666633,1098666633,4,False,True,NaN
C,A,20200101,2020,52,2020,842,USA,USA,X,Export,...,True,0,False,0.0,246332,246332,4,False,True,NaN
C,A,20200101,2020,52,2020,842,USA,USA,X,Export,...,True,0,False,0.0,88300,88300,4,False,True,NaN
C,A,20200101,2020,52,2020,842,USA,USA,X,Export,...,True,0,False,0.0,26125364,26125364,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,A,20240101,2024,52,2024,842,USA,USA,X,Export,...,False,0,False,NaN,1416601512,1416601512,0,False,True,NaN
C,A,20240101,2024,52,2024,842,USA,USA,X,Export,...,False,0,False,NaN,405815953,405815953,0,False,True,NaN
C,A,20240101,2024,52,2024,842,USA,USA,X,Export,...,False,0,False,NaN,3311564427,3311564427,0,False,True,NaN
C,A,20240101,2024,52,2024,842,USA,USA,X,Export,...,False,0,False,NaN,331536187,331536187,0,False,True,NaN
C,A,20240101,2024,52,2024,842,USA,USA,X,Export,...,False,0,False,NaN,4787227925,4787227925,0,False,True,NaN

In [128]:
col_drop2 = ["cmdDesc","isLeaf","qty","classificationSearchCode","altQty","partner2Desc","classificationCode","aggrLevel","mosCode","customsCode","customsDesc","partner2Code","partner2ISO","motCode","motDesc","qtyUnitCode","typeCode","period","reporterISO","reporterDesc","netWgt","isNetWgtEstimated","grossWgt","isGrossWgtEstimated","legacyEstimationFlag","isReported","isAggregate","qtyUnitAbbr","flowDesc","partnerDesc","isQtyEstimated","altQtyUnitCode","altQtyUnitAbbr","isAltQtyEstimated"]
df_exports.drop(columns=col_drop2, inplace=True)
df_exports

,freqCode,refPeriodId,refYear,refMonth,reporterCode,flowCode,partnerCode,partnerISO,isOriginalClassification,cmdCode,cifvalue,fobvalue,primaryValue
C,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4
C,20200101,2020,52,2020,USA,Export,CAN,Canada,96,Miscellaneous manufactured articles,1098666633,1098666633,4
C,20200101,2020,52,2020,USA,Export,EST,Estonia,96,Miscellaneous manufactured articles,246332,246332,4
C,20200101,2020,52,2020,USA,Export,AGO,Angola,96,Miscellaneous manufactured articles,88300,88300,4
C,20200101,2020,52,2020,USA,Export,DOM,Dominican Rep.,96,Miscellaneous manufactured articles,26125364,26125364,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,20240101,2024,52,2024,USA,Export,W00,World,41,Raw hides and skins (other than furskins) and ...,1416601512,1416601512,0
C,20240101,2024,52,2024,USA,Export,W00,World,58,"Fabrics; special woven fabrics, tufted textile...",405815953,405815953,0
C,20240101,2024,52,2024,USA,Export,W00,World,61,Apparel and clothing accessories; knitted or c...,3311564427,3311564427,0
C,20240101,2024,52,2024,USA,Export,W00,World,79,Zinc and articles thereof,331536187,331536187,0
C,20240101,2024,52,2024,USA,Export,W00,World,82,"Tools, implements, cutlery, spoons and forks, ...",4787227925,4787227925,0

In [129]:
df_exports = df_exports[df_exports["partnerISO"]!="World"]

In [130]:
df_exports = df_exports.rename(columns = {'freqCode':'YearMonthDay',
                                    "refPeriodId":"Year",
                                    "refYear":"Month",
                                    "refMonth":"YearMonth",
                                    "isOriginalClassification":"HS2",
                                    "cmdCode":"HS2 Description"})

In [131]:
export_pivot = df_exports.pivot_table(index="partnerISO", columns="Year", values="fobvalue", aggfunc="sum")

In [132]:
export_pivot = export_pivot / 1_000_000  # convert to millions
export_pivot = export_pivot.round(2)
export_pivot.fillna(0,inplace=True)
export_pivot

Year                      2020    2021     2022     2023     2024
partnerISO
Afghanistan             670.89  247.41    21.75    49.76    11.45
Albania                  56.90   97.56   117.84   139.25   141.72
Algeria                 726.29  783.63  1200.59  1214.45  1014.50
Andorra                   3.73    4.69     3.51     6.21     4.91
Angola                  470.52  449.39   651.45   595.28   682.35
...                        ...     ...      ...      ...      ...
Wallis and Futuna Isds    0.16    0.03     0.09     1.84     0.05
Western Sahara            6.82    0.00     0.00     0.00     0.00
Yemen                   331.13  271.80   382.00   178.79   134.10
Zambia                   71.82   94.14   135.31    94.49   113.76
Zimbabwe                 46.43   44.54    41.12    37.66    43.78

[224 rows x 5 columns]

In [153]:
df_imports = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\Imports_2020_2025.csv",dtype={"HS4": str}).drop(columns=["Unnamed: 0","cmdDesc","primaryValue"])
df_imports = df_imports[df_imports["partnerISO"]!="World"]
df_imports2 = df_imports
df_imports = df_imports[df_imports["Year"]!=2025]
df_imports

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,HS4 Description,cifvalue,fobvalue
0,20200101,2020,1,202001,USA,Import,ARG,Argentina,5701,Carpets and other textile floor coverings; kno...,8000,8650
1,20200101,2020,1,202001,USA,Import,FIN,Finland,5701,Carpets and other textile floor coverings; kno...,1478,1511
2,20200101,2020,1,202001,USA,Import,ZAF,South Africa,5701,Carpets and other textile floor coverings; kno...,15063,16337
3,20200101,2020,1,202001,USA,Import,ARM,Armenia,5701,Carpets and other textile floor coverings; kno...,4334,4534
4,20200101,2020,1,202001,USA,Import,HUN,Hungary,5701,Carpets and other textile floor coverings; kno...,29655,29656
...,...,...,...,...,...,...,...,...,...,...,...,...
2163200,20241201,2024,12,202412,USA,Import,EGY,Egypt,9701,"Paintings, drawings and pastels, executed enti...",8000,8071
2163201,20241201,2024,12,202412,USA,Import,SAU,Saudi Arabia,9032,Regulating or controlling instruments and appa...,3236,3243
2163202,20241201,2024,12,202412,USA,Import,SWE,Sweden,8712,Bicycles and other cycles; including delivery ...,5750,5906
2163203,20241201,2024,12,202412,USA,Import,SLV,El Salvador,8701,Tractors; (other than tractors of heading no 8...,350000,351000
2163204,20241201,2024,12,202412,USA,Import,AUT,Austria,9104,Instrument panel clocks and clocks of a simila...,4390,4840

In [134]:
import_pivot = df_imports.pivot_table(index="partnerISO", columns="Year", values="fobvalue", aggfunc="sum")
import_pivot = import_pivot / 1_000_000  # convert to millions
import_pivot = import_pivot.round(2)
import_pivot.fillna(0,inplace=True)
import_pivot

Year                      2020     2021     2022     2023     2024
partnerISO
Afghanistan              17.33    22.77    26.53    21.01    23.77
Albania                  48.82    70.62   152.44    80.75   133.15
Algeria                 498.85  1907.30  2867.46  3150.87  2540.86
Andorra                   5.49     8.23     9.98    53.54     3.33
Angola                  497.35  1089.25  1676.48  1205.19  1912.51
...                        ...      ...      ...      ...      ...
Wallis and Futuna Isds    0.80     0.11     0.14     0.06     0.04
Western Sahara            0.02     0.00     0.00     0.00     0.00
Yemen                     4.14    10.80    27.44     7.23     9.33
Zambia                   41.47   178.65   138.53   157.19   171.47
Zimbabwe                 37.99    44.24   101.80   119.69    69.53

[224 rows x 5 columns]

In [135]:
export_pivot

Year                      2020    2021     2022     2023     2024
partnerISO
Afghanistan             670.89  247.41    21.75    49.76    11.45
Albania                  56.90   97.56   117.84   139.25   141.72
Algeria                 726.29  783.63  1200.59  1214.45  1014.50
Andorra                   3.73    4.69     3.51     6.21     4.91
Angola                  470.52  449.39   651.45   595.28   682.35
...                        ...     ...      ...      ...      ...
Wallis and Futuna Isds    0.16    0.03     0.09     1.84     0.05
Western Sahara            6.82    0.00     0.00     0.00     0.00
Yemen                   331.13  271.80   382.00   178.79   134.10
Zambia                   71.82   94.14   135.31    94.49   113.76
Zimbabwe                 46.43   44.54    41.12    37.66    43.78

[224 rows x 5 columns]

In [136]:
diff = export_pivot.subtract(import_pivot).reset_index()
diff.fillna(0,inplace=True)
diff.head(50)

Year,partnerISO,2020,2021,2022,2023,2024
0,Afghanistan,653.56,224.64,-4.78,28.75,-12.32
1,Albania,8.08,26.94,-34.60,58.50,8.57
2,Algeria,227.44,-1123.67,-1666.87,-1936.42,-1526.36
3,Andorra,-1.76,-3.54,-6.47,-47.33,1.58
4,Angola,-26.83,-639.86,-1025.03,-609.91,-1230.16
5,Anguilla,45.37,80.28,80.71,68.97,71.19
6,Antigua and Barbuda,307.90,526.50,1018.21,963.91,549.72
7,Argentina,1571.93,2347.29,5743.21,4711.68,1760.25
8,Armenia,-42.56,-45.47,112.65,50.04,31.75
9,Aruba,274.30,508.10,624.87,621.59,714.51
10,Australia,9138.67,14561.51,13582.23,18358.92,18016.32
11,Austria,-8368.87,-11310.22,-13841.90,-13963.49,-13453.01
12,Azerbaijan,122.78,24.55,22.65,469.94,92.31
13,Bahamas,2580.95,2442.22,3723.73,3707.54,3800.59
14,Bahrain,215.41,-302.13,-1002.73,444.89,373.95
15,Bangladesh,-4464.05,-6458.52,-9281.32,-6416.71,-6566.96
16,Barbados,466.95,669.74,758.99,665.67,720.88
17,Belarus,-242.71,-288.37,-178.26,-33.08,-10.61
18,Belgium,6255.00,12114.24,7943.99,15326.84,5903.44
19,Belize,340.30,370.64,476.16,590.70,504.08
20,Benin,191.73,310.60,284.49,226.99,162.96
21,Bermuda,439.87,540.36,566.27,532.49,516.57
22,Bhutan,2.43,5.54,4.58,2.64,-0.10
23,Bolivia (Plurinational State of),61.72,23.10,-125.88,81.21,-114.29
24,Bosnia Herzegovina,-80.44,-120.34,-151.69,-135.02,-133.18
25,Botswana,-129.57,-204.95,-415.55,-432.93,-310.68
26,Br. Indian Ocean Terr.,7.12,5.67,4.43,2.68,4.99
27,Br. Virgin Isds,275.62,271.36,520.91,443.03,252.46
28,Brazil,10625.24,14039.03,12733.05,3809.55,5483.83
29,Brunei Darussalam,28.72,79.09,11.32,-105.25,-121.35
30,Bulgaria,-509.64,-864.34,-1049.39,-1055.08,-1041.20
31,Burkina Faso,67.06,93.36,59.67,41.98,49.67
32,Burundi,1.42,0.56,-3.54,-2.43,2.81
33,Cabo Verde,1.89,6.94,8.32,55.34,7.56
34,Cambodia,-6539.90,-8957.57,-12738.17,-11822.12,-13043.20
35,Cameroon,-258.35,-66.05,86.20,76.20,-67.27
36,Canada,-21173.93,-56977.94,-89839.67,-76844.81,-72792.36
37,Cayman Isds,727.98,1162.28,1387.46,1250.60,1225.27
38,Central African Rep.,21.34,15.70,24.24,14.81,33.60
39,Chad,42.53,37.72,76.45,-54.93,-22.79
40,Chile,1849.53,1379.59,6814.11,2100.42,754.93
41,China,-332515.71,-390466.17,-424026.77,-300211.86,-319074.62
42,"China, Hong Kong SAR",15945.40,25570.85,20805.65,23486.80,21817.73
43,"China, Macao SAR",79.06,65.78,74.33,387.87,163.03
44,Christmas Isds,1.50,-0.78,0.51,44.42,0.27
45,Cocos Isds,-1.66,-2.00,0.72,-1.64,1.45
46,Colombia,752.70,2720.73,1559.13,594.45,604.35
47,Comoros,-2.03,-4.63,-3.31,-2.39,2.87
48,Congo,-37.51,58.08,26.75,-103.90,195.52
49,Cook Isds,0.77,2.91,5.24,4.80,5.97

In [137]:
diff.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\balance.csv")
import_pivot.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\import_pivot.csv")
export_pivot.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\export_pivot.csv")

In [138]:
#function application on both datasets
df_imports["HS4"] = df_imports["HS4"].str.zfill(4)

In [151]:
HS_table = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\HS_codes_improved.csv",dtype={"HS4": str}).drop(columns="Unnamed: 0").drop_duplicates(subset=['HS4'], keep='first')
HS_table.head(50)

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example,Tariff
0,5701,Carpets and other textile floor coverings; kno...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
1,5702,Carpets and other textile floor coverings; wov...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
2,5703,Carpets and other textile floor coverings; tuf...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
3,5704,Carpets and other textile floor coverings; of ...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
4,5705,Carpets and other textile floor coverings; n.e...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
5,5904,"Linoleum, whether or not cut to shape; floor c...",59,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
6,5905,Textile wall coverings,59,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
7,6907,"Ceramic flags and paving, hearth or wall tiles...",69,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Not Applied
8,7003,Glass; cast glass and rolled glass in sheets o...,70,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Not Applied
9,7004,"Glass; drawn glass and blown glass, in sheets,...",70,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Not Applied
10,7005,Glass; float glass and surface ground or polis...,70,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Not Applied
11,7007,"Safety glass, consisting of toughened (tempere...",70,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Applied
12,3701,"Photographic plates and film in the flat, sens...",37,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
13,3702,"Photographic film in rolls, sensitised, unexpo...",37,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
14,6401,"Footwear; waterproof, with outer soles and upp...",64,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
15,6402,Footwear; with outer soles and uppers of rubbe...,64,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
16,6403,"Footwear; with outer soles of rubber, plastics...",64,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
17,6404,"Footwear; with outer soles of rubber, plastics...",64,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
18,6405,Footwear; other footwear n.e.c. in chapter 64,64,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
19,4403,"Wood in the rough, whether or not stripped of ...",44,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",Not Applied
20,4406,Railway or tramway sleepers (cross-ties) of wood,44,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",Not Applied
21,4407,"Wood sawn or chipped lengthwise, sliced or pee...",44,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",Not Applied
22,4412,"Plywood, veneered panels and similar laminated...",44,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",Not Applied
23,2804,"Hydrogen, rare gases and other non-metals",28,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
24,6904,"Ceramic building bricks, floor blocks, support...",69,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",Not Applied
25,2716,Electrical energy,27,V,25 - 27,Mineral Products,"Salt, coal, crude oil",Not Applied
26,3706,"Cinematographic film; exposed and developed, w...",37,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
27,9506,"Gymnastics, athletics, other sports (including...",95,XX,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",Applied
28,9001,Optical fibres and optical fibre bundles; opti...,90,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",Not Applied
29,6101,"Coats; men's or boys' overcoats, car-coats, ca...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
30,6102,"Coats; women's or girls' overcoats, car-coats,...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
31,6105,"Shirts; men's or boys', knitted or crocheted",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
32,6106,"Blouses, shirts and shirt-blouses; women's or ...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
33,6107,"Underpants, briefs, nightshirts, pyjamas, bath...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
34,6108,"Slips, petticoats, briefs, panties, nightdress...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
35,6109,"T-shirts, singlets and other vests; knitted or...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
36,6110,"Jerseys, pullovers, cardigans, waistcoats and ...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
37,6112,"Track suits, ski suits and swimwear; knitted o...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
38,6201,"Overcoats, car-coats, capes, cloaks, anoraks (...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
39,6202,"Coats; women's or girls' overcoats, carcoats, ...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
40,6205,Shirts; men's or boys' (not knitted or crocheted),62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
41,6206,"Blouses, shirts and shirt-blouses; women's or ...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
42,6214,"Shawls, scarves, mufflers, mantillas, veils an...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
43,6601,Umbrellas; sun umbrellas (including walking st...,66,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Not Applied
44,9004,"Spectacles, goggles and the like; corrective, ...",90,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",Not Applied
45,6103,"Suits, ensembles, jackets, blazers, trousers, ...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
46,6104,"Suits, ensembles, jackets, dresses, skirts, di...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
47,6117,"Clothing accessories; made up, knitted or croc...",61,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
48,6203,"Suits, ensembles, jackets, blazers, trousers, ...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
49,6204,"Suits, ensembles, jackets, dresses, skirts, di...",62,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied

In [140]:
df_imports2 = pd.merge(df_imports,HS_table,how="left",on="HS4").drop(columns=["HS2","Section","Chapter Range","Example","HS4 Description_y"])
df_imports2

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,HS4 Description_x,cifvalue,fobvalue,Section Title,Tariff
0,20200101,2020,1,202001,USA,Import,ARG,Argentina,5701,Carpets and other textile floor coverings; kno...,8000,8650,Textiles and Textile Articles,Not Applied
1,20200101,2020,1,202001,USA,Import,FIN,Finland,5701,Carpets and other textile floor coverings; kno...,1478,1511,Textiles and Textile Articles,Not Applied
2,20200101,2020,1,202001,USA,Import,ZAF,South Africa,5701,Carpets and other textile floor coverings; kno...,15063,16337,Textiles and Textile Articles,Not Applied
3,20200101,2020,1,202001,USA,Import,ARM,Armenia,5701,Carpets and other textile floor coverings; kno...,4334,4534,Textiles and Textile Articles,Not Applied
4,20200101,2020,1,202001,USA,Import,HUN,Hungary,5701,Carpets and other textile floor coverings; kno...,29655,29656,Textiles and Textile Articles,Not Applied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090457,20241201,2024,12,202412,USA,Import,EGY,Egypt,9701,"Paintings, drawings and pastels, executed enti...",8000,8071,"Works of Art, Collectors’ Pieces, and Special ...",Not Applied
2090458,20241201,2024,12,202412,USA,Import,SAU,Saudi Arabia,9032,Regulating or controlling instruments and appa...,3236,3243,"Optical, Precision, Medical Instruments",Not Applied
2090459,20241201,2024,12,202412,USA,Import,SWE,Sweden,8712,Bicycles and other cycles; including delivery ...,5750,5906,"Vehicles, Aircraft, and Vessels",Not Applied
2090460,20241201,2024,12,202412,USA,Import,SLV,El Salvador,8701,Tractors; (other than tractors of heading no 8...,350000,351000,"Vehicles, Aircraft, and Vessels",Applied
2090461,20241201,2024,12,202412,USA,Import,AUT,Austria,9104,Instrument panel clocks and clocks of a simila...,4390,4840,"Optical, Precision, Medical Instruments",Not Applied

In [141]:
df_exports2 = pd.merge(df_exports,HS_table,how="left",on="HS2").drop(columns=["HS4","Section","Chapter Range","Example","HS4 Description"])
df_exports2

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS2,HS2 Description,cifvalue,fobvalue,primaryValue,Section Title,Tariff
0,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4,Miscellaneous Manufactured Articles,Not Applied
1,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4,Miscellaneous Manufactured Articles,Not Applied
2,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4,Miscellaneous Manufactured Articles,Not Applied
3,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4,Miscellaneous Manufactured Articles,Not Applied
4,20200101,2020,52,2020,USA,Export,ARM,Armenia,96,Miscellaneous manufactured articles,29282,29282,4,Miscellaneous Manufactured Articles,Not Applied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033621,20240101,2024,52,2024,USA,Export,KGZ,Kyrgyzstan,91,Clocks and watches and parts thereof,9155,9155,0,"Optical, Precision, Medical Instruments",Not Applied
1033622,20240101,2024,52,2024,USA,Export,KGZ,Kyrgyzstan,91,Clocks and watches and parts thereof,9155,9155,0,"Optical, Precision, Medical Instruments",Not Applied
1033623,20240101,2024,52,2024,USA,Export,KGZ,Kyrgyzstan,91,Clocks and watches and parts thereof,9155,9155,0,"Optical, Precision, Medical Instruments",Not Applied
1033624,20240101,2024,52,2024,USA,Export,KGZ,Kyrgyzstan,91,Clocks and watches and parts thereof,9155,9155,0,"Optical, Precision, Medical Instruments",Not Applied
1033625,20240101,2024,52,2024,USA,Export,KGZ,Kyrgyzstan,91,Clocks and watches and parts thereof,9155,9155,0,"Optical, Precision, Medical Instruments",Not Applied

In [149]:
pivot_imp_prod = df_imports2.pivot_table(index=["Section Title","HS4","partnerISO"],columns="Year",values="fobvalue",aggfunc="sum")
pivot_imp_prod = (pivot_imp_prod / 1_000_000).round(2)
pivot_imp_prod.fillna(0,inplace=True)
pivot_imp_prod

Year                                                                             2020  \
Section Title                                      HS4  partnerISO
Animal or Vegetable Fats and Oils                  1501 Brazil                   0.00
                                                        Canada                  17.65
                                                        Denmark                  0.00
                                                        France                   0.27
                                                        Japan                    0.00
...                                                                               ...
Works of Art, Collectors’ Pieces, and Special T... 9999 Wallis and Futuna Isds   0.05
                                                        Western Sahara           0.00
                                                        Yemen                    0.13
                                                        Zambia                   1.17
                                                        Zimbabwe                 0.15

Year                                                                             2021  \
Section Title                                      HS4  partnerISO
Animal or Vegetable Fats and Oils                  1501 Brazil                   0.00
                                                        Canada                  34.67
                                                        Denmark                  0.00
                                                        France                   0.06
                                                        Japan                    0.00
...                                                                               ...
Works of Art, Collectors’ Pieces, and Special T... 9999 Wallis and Futuna Isds   0.00
                                                        Western Sahara           0.00
                                                        Yemen                    0.24
                                                        Zambia                   0.86
                                                        Zimbabwe                 0.63

Year                                                                             2022  \
Section Title                                      HS4  partnerISO
Animal or Vegetable Fats and Oils                  1501 Brazil                   1.51
                                                        Canada                  66.28
                                                        Denmark                  0.00
                                                        France                   0.04
                                                        Japan                    0.00
...                                                                               ...
Works of Art, Collectors’ Pieces, and Special T... 9999 Wallis and Futuna Isds   0.00
                                                        Western Sahara           0.00
                                                        Yemen                    0.12
                                                        Zambia                   2.96
                                                        Zimbabwe                 0.38

Year                                                                             2023  \
Section Title                                      HS4  partnerISO
Animal or Vegetable Fats and Oils                  1501 Brazil                  30.50
                                                        Canada                  53.94
                                                        Denmark                  0.00
                                                        France                   0.05
                                                        Japan                    0.00
...                                                                               ...
Works of Art, Collectors’ Pieces, and Special T... 9999 Wallis and Futuna Isds   0.00
                                                        Western Sahara           0.00
                                                        Yemen                    0.45
                                                        Zambia                   0.64
                                                        Zimbabwe                 1.11

Year                                                                             2024
Section Title                                      HS4  partnerISO
Animal or Vegetable Fats and Oils                  1501 Brazil                  37.00
                                                        Canada                  44.18
                                                        Denmark                  0.00
                                                        France                   0.04
                                                        Japan                    0.00
...                                                                               ...
Works of Art, Collectors’ Pieces, and Special T... 9999 Wallis and Futuna Isds   0.02
                                                        Western Sahara           0.00
                                                        Yemen                    0.16
                                                        Zambia                   1.22
                                                        Zimbabwe                 0.85

[82350 rows x 5 columns]

In [143]:
pivot_exp_prod = df_exports2.pivot_table(index=["Section Title","partnerISO"],columns="Year",values="fobvalue",aggfunc="sum")
pivot_exp_prod = (pivot_exp_prod / 1_000_000).round(2)
pivot_exp_prod.fillna(0,inplace=True)
pivot_exp_prod

Year                                                                         2020  \
Section Title                                      partnerISO
Animal or Vegetable Fats and Oils                  Afghanistan               5.38
                                                   Albania                   0.00
                                                   Algeria                 355.12
                                                   Angola                    0.24
                                                   Anguilla                  1.91
...                                                                           ...
Works of Art, Collectors’ Pieces, and Special T... Wallis and Futuna Isds    0.01
                                                   Western Sahara            0.11
                                                   Yemen                     6.29
                                                   Zambia                    4.35
                                                   Zimbabwe                  0.95

Year                                                                         2021  \
Section Title                                      partnerISO
Animal or Vegetable Fats and Oils                  Afghanistan               0.00
                                                   Albania                   0.00
                                                   Algeria                 620.14
                                                   Angola                    0.00
                                                   Anguilla                  6.13
...                                                                           ...
Works of Art, Collectors’ Pieces, and Special T... Wallis and Futuna Isds    0.00
                                                   Western Sahara            0.00
                                                   Yemen                     3.97
                                                   Zambia                    5.37
                                                   Zimbabwe                  2.01

Year                                                                       2022  \
Section Title                                      partnerISO
Animal or Vegetable Fats and Oils                  Afghanistan             0.00
                                                   Albania                 0.00
                                                   Algeria                 0.50
                                                   Angola                  2.83
                                                   Anguilla                8.85
...                                                                         ...
Works of Art, Collectors’ Pieces, and Special T... Wallis and Futuna Isds  0.00
                                                   Western Sahara          0.00
                                                   Yemen                   4.36
                                                   Zambia                  7.26
                                                   Zimbabwe                2.32

Year                                                                       2023  \
Section Title                                      partnerISO
Animal or Vegetable Fats and Oils                  Afghanistan             0.00
                                                   Albania                 0.00
                                                   Algeria                 0.75
                                                   Angola                  2.89
                                                   Anguilla                7.61
...                                                                         ...
Works of Art, Collectors’ Pieces, and Special T... Wallis and Futuna Isds  0.21
                                                   Western Sahara          0.00
                                                   Yemen                   4.34
                                                   Zambia                  5.81
                                                   Zimbabwe                0.75

Year                                                                         2024
Section Title                                      partnerISO
Animal or Vegetable Fats and Oils                  Afghanistan               0.00
                                                   Albania                   0.37
                                                   Algeria                 704.29
                                                   Angola                    0.11
                                                   Anguilla                  7.92
...                                                                           ...
Works of Art, Collectors’ Pieces, and Special T... Wallis and Futuna Isds    0.01
                                                   Western Sahara            0.00
                                                   Yemen                     1.66
                                                   Zambia                    7.12
                                                   Zimbabwe                  1.34

[4400 rows x 5 columns]

In [144]:
#pivot_exp_prod[2024].sum()/1000000

In [147]:
pivot_imp_prod.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\pivot_imp_prod.csv")
pivot_exp_prod.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\pivot_exp_prod.csv")

In [156]:
df_imports2

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,HS4 Description,cifvalue,fobvalue
0,20200101,2020,1,202001,USA,Import,ARG,Argentina,5701,Carpets and other textile floor coverings; kno...,8000,8650
1,20200101,2020,1,202001,USA,Import,FIN,Finland,5701,Carpets and other textile floor coverings; kno...,1478,1511
2,20200101,2020,1,202001,USA,Import,ZAF,South Africa,5701,Carpets and other textile floor coverings; kno...,15063,16337
3,20200101,2020,1,202001,USA,Import,ARM,Armenia,5701,Carpets and other textile floor coverings; kno...,4334,4534
4,20200101,2020,1,202001,USA,Import,HUN,Hungary,5701,Carpets and other textile floor coverings; kno...,29655,29656
...,...,...,...,...,...,...,...,...,...,...,...,...
2530251,20251001,2025,10,202510,USA,Import,CHN,China,4418,"Builders' joinery and carpentry of wood, inclu...",5491768,6303897
2530252,20251001,2025,10,202510,USA,Import,CHN,China,4817,"Envelopes, letter cards, plain postcards and c...",1544374,1667823
2530253,20251001,2025,10,202510,USA,Import,CHN,China,4820,"Registers, account books, diaries and similar;...",12231544,13049375
2530254,20251001,2025,10,202510,USA,Import,CHN,China,4901,"Printed books, brochures, leaflets and similar...",64541311,68754279
2530255,20251001,2025,10,202510,USA,Import,CHN,China,5603,"Nonwovens; whether or not impregnated, coated,...",26792384,29831067

In [163]:
df_imports2.drop_duplicates(inplace=True)

In [ ]:
pivot_impact_imports = round(df_imports2.pivot_table(index=["Year","Month","partnerISO"], values="fobvalue", aggfunc="sum")/1000000,2)
pivot_impact_imports

                        fobvalue
Year Month partnerISO
2020 1     Afghanistan      2.31
           Albania          4.07
           Algeria        102.98
           Andorra          0.12
           Angola          19.31
...                          ...
2025 10    Venezuela      305.85
           Viet Nam     18438.96
           Yemen            0.56
           Zambia           3.86
           Zimbabwe         2.64

[15090 rows x 1 columns]

In [ ]:
pivot_impact_imports.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\pivot_impact_imports.csv")

In [174]:
HS_table

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example,Tariff
0,5701,Carpets and other textile floor coverings; kno...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
1,5702,Carpets and other textile floor coverings; wov...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
2,5703,Carpets and other textile floor coverings; tuf...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
3,5704,Carpets and other textile floor coverings; of ...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
4,5705,Carpets and other textile floor coverings; n.e...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
...,...,...,...,...,...,...,...,...
1282,0309,"Flours, meals and pellets of fish, crustaceans...",3,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",Not Applied
1284,3827,Mixtures containing halogenated derivatives of...,38,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
1285,8806,Unmanned aircraft,88,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",Not Applied
1286,2404,"Products containing tobacco, reconstituted tob...",24,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",Not Applied
1287,1203,Copra,12,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",Not Applied

In [179]:
HS_table[(HS_table["Tariff"]=="Applied") & (HS_table["Section Title"]=="Footwear, Headgear, Umbrellas")]

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example,Tariff
353,6603,"Trimmings, parts and accessories of articles o...",66,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",Applied

In [184]:
HS_imp_prod = HS_table.pivot_table(index="Section Title",columns="Tariff",values="HS4",aggfunc="nunique").fillna(0).reset_index().sort_values(by=["Applied","Not Applied"],ascending=False)
HS_imp_prod["Applied"] = HS_imp_prod["Applied"].astype(int)
HS_imp_prod["Not Applied"] = HS_imp_prod["Not Applied"].astype(int)
HS_imp_prod

Tariff,Section Title,Applied,Not Applied
3,Base Metals and Articles of Base Metal,64,84
7,Machinery and Electrical Equipment,45,89
18,"Vehicles, Aircraft, and Vessels",9,31
9,Miscellaneous Manufactured Articles,7,25
10,"Optical, Precision, Medical Instruments",6,47
12,Plastics and Rubber,5,38
2,"Articles of Stone, Cement, Ceramic, and Glass",2,45
5,"Footwear, Headgear, Umbrellas",1,18
4,Chemicals and Allied Industries,0,179
16,Textiles and Textile Articles,0,152
17,Vegetable Products,0,77
8,Mineral Products,0,66
13,Prepared Foodstuffs; Beverages; Tobacco,0,57
6,Live Animals; Animal Products,0,44
14,Pulp of Wood; Paper; Printing Industry Products,0,40
19,Wood and Articles of Wood,0,27
0,Animal or Vegetable Fats and Oils,0,21
15,"Raw Hides, Skins, Leather, and Furskins",0,20
11,"Pearls, Precious Stones and Metals",0,18
1,Arms and Ammunition,0,7
20,"Works of Art, Collectors’ Pieces, and Special ...",0,7

In [185]:
HS_imp_prod.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\pivot_impact_products_bysection.csv")

In [193]:
df_imp_prod = pd.merge(df_imports2,HS_table,how="left",on="HS4")
df_imp_prod.drop(columns=["cifvalue","HS4 Description_x","Section"],inplace=True)
df_imp_prod = df_imp_prod[(df_imp_prod["Tariff"] == "Applied") &(df_imp_prod["Year"].isin([2024, 2025]))]
df_imp_prod["fobvalue"] = df_imp_prod["fobvalue"]/1000000
df_imp_prod

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,fobvalue,HS4 Description_y,HS2,Chapter Range,Section Title,Example,Tariff
1629980,20240101,2024,1,202401,USA,Import,GIN,Guinea,8479,0.003874,Machinery and mechanical appliances; having in...,84,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied
1629984,20240101,2024,1,202401,USA,Import,JOR,Jordan,8479,0.022171,Machinery and mechanical appliances; having in...,84,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied
1629985,20240101,2024,1,202401,USA,Import,KEN,Kenya,8479,0.017391,Machinery and mechanical appliances; having in...,84,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied
1629988,20240101,2024,1,202401,USA,Import,COL,Colombia,8501,0.564665,Electric motors and generators (excluding gene...,85,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied
1629991,20240101,2024,1,202401,USA,Import,CYP,Cyprus,8501,0.003451,Electric motors and generators (excluding gene...,85,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2410204,20251001,2025,10,202510,USA,Import,CHN,China,8708,636.771726,"Motor vehicles; parts and accessories, of head...",87,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",Applied
2410208,20251001,2025,10,202510,USA,Import,CHN,China,9020,0.451046,Breathing appliances and gas masks; excluding ...,90,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",Applied
2410213,20251001,2025,10,202510,USA,Import,CHN,China,9405,149.488699,"Lamps, light fittings; including searchlights,...",94,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",Applied
2410214,20251001,2025,10,202510,USA,Import,CHN,China,9406,14.323808,Buildings; prefabricated,94,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",Applied
2410233,20251001,2025,10,202510,USA,Import,CHN,China,8503,38.253845,Electric motors and generators; parts suitable...,85,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",Applied

In [194]:
df_imp_prod.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\impact_products_HS4.csv")