In [ ]:
### This notebook has the purpose of loading several pdf files of US Tariff Proclamations in order to retrieve the HS codes affected in each

In [1]:
import pandas as pd
import pdfplumber
import re

pdf_path = r"C:\Users\rcrds\Desktop\Ironhack\Final Project\steelHTSlist final (1).pdf"

steel_codes = set()

with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        
        if text:
            matches = re.findall(r"\b(72\d{2}|73\d{2}|84\d{2}|85\d{2}|94\d{2})\b", text)

            for m in matches:
                steel_codes.add(m)
steel_hs4 = sorted(steel_codes)

print("Steel HS4 Codes Covered:")
print(steel_hs4)

Steel HS4 Codes Covered:
['7206', '7207', '7208', '7209', '7210', '7211', '7212', '7213', '7214', '7215', '7216', '7217', '7218', '7219', '7220', '7221', '7222', '7223', '7224', '7225', '7226', '7227', '7228', '7229', '7301', '7302', '7304', '7305', '7306', '7307', '7308', '7309', '7310', '7311', '7312', '7313', '7314', '7315', '7316', '7317', '7318', '7319', '7320', '7321', '7322', '7323', '7324', '7325', '7326', '8431', '8432', '8547', '9403', '9405', '9406']

In [2]:
pdf_path2 = r"C:\Users\rcrds\Desktop\Ironhack\Final Project\aluminumHTSlist final.pdf"

aluminum_codes = set()

with pdfplumber.open(pdf_path2) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        
        if text:
            matches = re.findall(r"\b(76\d{2}|87\d{2}|66\d{2}|83\d{2}|84\d{2}|85\d{2}|88\d{2}|90\d{2}|94\d{2}|95\d{2}|96\d{2})\b", text)

            for m in matches:
                aluminum_codes.add(m)
aluminum_hs4 = sorted(aluminum_codes)

print("Aluminum HS4 Codes Covered:")
print(aluminum_hs4)

Aluminum HS4 Codes Covered:
['6603', '7601', '7604', '7605', '7606', '7607', '7608', '7609', '7610', '7614', '7615', '7616', '8302', '8305', '8306', '8414', '8415', '8418', '8419', '8422', '8424', '8473', '8479', '8481', '8486', '8487', '8500', '8503', '8508', '8513', '8515', '8516', '8517', '8529', '8536', '8538', '8541', '8543', '8547', '8585', '8701', '8705', '8708', '8716', '8807', '8885', '9000', '9010', '9013', '9015', '9020', '9031', '9040', '9045', '9060', '9080', '9081', '9085', '9090', '9401', '9403', '9405', '9506', '9507', '9520', '9596', '9599', '9603']

In [3]:
pdf_path3 = r"C:\Users\rcrds\Desktop\Ironhack\Final Project\autoparts final.pdf"

auto_parts_codes = set()

with pdfplumber.open(pdf_path3) as pdf:
    for page in pdf.pages:
        text = page.extract_text()
        
        if text:
            matches = re.findall(r"\b(87\d{2}|40\d{2}|73\d{2}|83\d{2}|84\d{2}|85\d{2}|70\d{2}|90\d{2}|94\d{2})\b", text)

            for m in matches:
                auto_parts_codes.add(m)
auto_parts_hs4 = sorted(auto_parts_codes)

print("Auto Parts HS4 Codes Covered:")
print(auto_parts_hs4)

Auto Parts HS4 Codes Covered:
['4009', '4011', '4012', '4013', '4016', '4080', '7007', '7009', '7320', '8301', '8302', '8407', '8408', '8409', '8413', '8414', '8415', '8421', '8425', '8426', '8431', '8471', '8482', '8483', '8501', '8507', '8511', '8512', '8519', '8525', '8527', '8536', '8537', '8539', '8544', '8706', '8707', '8708', '8716', '9010', '9015', '9029', '9401']

In [4]:
automotive_codes = ["8703","8704"]
automotive_codes

['8703', '8704']

In [13]:
steel_df = pd.DataFrame(steel_hs4)
steel_df.rename(columns={0:"HS4"},inplace=True)
steel_df["Tariff"] = "Applied"
steel_df["Scope"] = "Steel"
steel_df

     HS4   Tariff  Scope
0   7206  Applied  Steel
1   7207  Applied  Steel
2   7208  Applied  Steel
3   7209  Applied  Steel
4   7210  Applied  Steel
5   7211  Applied  Steel
6   7212  Applied  Steel
7   7213  Applied  Steel
8   7214  Applied  Steel
9   7215  Applied  Steel
10  7216  Applied  Steel
11  7217  Applied  Steel
12  7218  Applied  Steel
13  7219  Applied  Steel
14  7220  Applied  Steel
15  7221  Applied  Steel
16  7222  Applied  Steel
17  7223  Applied  Steel
18  7224  Applied  Steel
19  7225  Applied  Steel
20  7226  Applied  Steel
21  7227  Applied  Steel
22  7228  Applied  Steel
23  7229  Applied  Steel
24  7301  Applied  Steel
25  7302  Applied  Steel
26  7304  Applied  Steel
27  7305  Applied  Steel
28  7306  Applied  Steel
29  7307  Applied  Steel
30  7308  Applied  Steel
31  7309  Applied  Steel
32  7310  Applied  Steel
33  7311  Applied  Steel
34  7312  Applied  Steel
35  7313  Applied  Steel
36  7314  Applied  Steel
37  7315  Applied  Steel
38  7316  Applied  Steel
39  7317  Applied  Steel
40  7318  Applied  Steel
41  7319  Applied  Steel
42  7320  Applied  Steel
43  7321  Applied  Steel
44  7322  Applied  Steel
45  7323  Applied  Steel
46  7324  Applied  Steel
47  7325  Applied  Steel
48  7326  Applied  Steel
49  8431  Applied  Steel
50  8432  Applied  Steel
51  8547  Applied  Steel
52  9403  Applied  Steel
53  9405  Applied  Steel
54  9406  Applied  Steel

In [14]:
aluminum_df = pd.DataFrame(aluminum_hs4)
aluminum_df.rename(columns={0:"HS4"},inplace=True)
aluminum_df["Tariff"] = "Applied"
aluminum_df["Scope"] = "Aluminum"
aluminum_df

     HS4   Tariff     Scope
0   6603  Applied  Aluminum
1   7601  Applied  Aluminum
2   7604  Applied  Aluminum
3   7605  Applied  Aluminum
4   7606  Applied  Aluminum
..   ...      ...       ...
63  9507  Applied  Aluminum
64  9520  Applied  Aluminum
65  9596  Applied  Aluminum
66  9599  Applied  Aluminum
67  9603  Applied  Aluminum

[68 rows x 3 columns]

In [15]:
autoparts_df = pd.DataFrame(auto_parts_hs4)
autoparts_df.rename(columns={0:"HS4"},inplace=True)
autoparts_df["Tariff"] = "Applied"
autoparts_df["Scope"] = "Auto Parts"
autoparts_df

     HS4   Tariff       Scope
0   4009  Applied  Auto Parts
1   4011  Applied  Auto Parts
2   4012  Applied  Auto Parts
3   4013  Applied  Auto Parts
4   4016  Applied  Auto Parts
5   4080  Applied  Auto Parts
6   7007  Applied  Auto Parts
7   7009  Applied  Auto Parts
8   7320  Applied  Auto Parts
9   8301  Applied  Auto Parts
10  8302  Applied  Auto Parts
11  8407  Applied  Auto Parts
12  8408  Applied  Auto Parts
13  8409  Applied  Auto Parts
14  8413  Applied  Auto Parts
15  8414  Applied  Auto Parts
16  8415  Applied  Auto Parts
17  8421  Applied  Auto Parts
18  8425  Applied  Auto Parts
19  8426  Applied  Auto Parts
20  8431  Applied  Auto Parts
21  8471  Applied  Auto Parts
22  8482  Applied  Auto Parts
23  8483  Applied  Auto Parts
24  8501  Applied  Auto Parts
25  8507  Applied  Auto Parts
26  8511  Applied  Auto Parts
27  8512  Applied  Auto Parts
28  8519  Applied  Auto Parts
29  8525  Applied  Auto Parts
30  8527  Applied  Auto Parts
31  8536  Applied  Auto Parts
32  8537  Applied  Auto Parts
33  8539  Applied  Auto Parts
34  8544  Applied  Auto Parts
35  8706  Applied  Auto Parts
36  8707  Applied  Auto Parts
37  8708  Applied  Auto Parts
38  8716  Applied  Auto Parts
39  9010  Applied  Auto Parts
40  9015  Applied  Auto Parts
41  9029  Applied  Auto Parts
42  9401  Applied  Auto Parts

In [16]:
automotive_df = pd.DataFrame(automotive_codes)
automotive_df.rename(columns={0:"HS4"},inplace=True)
automotive_df["Tariff"] = "Applied"
automotive_df["Scope"] = "Automotive"
automotive_df

    HS4   Tariff       Scope
0  8703  Applied  Automotive
1  8704  Applied  Automotive

In [21]:
AffectedHS = pd.concat([steel_df,aluminum_df,autoparts_df,automotive_df]).sort_values(by="HS4")
AffectedHS.tail(50)

     HS4   Tariff       Scope
32  8537  Applied  Auto Parts
35  8538  Applied    Aluminum
33  8539  Applied  Auto Parts
36  8541  Applied    Aluminum
37  8543  Applied    Aluminum
34  8544  Applied  Auto Parts
51  8547  Applied       Steel
38  8547  Applied    Aluminum
39  8585  Applied    Aluminum
40  8701  Applied    Aluminum
0   8703  Applied  Automotive
1   8704  Applied  Automotive
41  8705  Applied    Aluminum
35  8706  Applied  Auto Parts
36  8707  Applied  Auto Parts
42  8708  Applied    Aluminum
37  8708  Applied  Auto Parts
38  8716  Applied  Auto Parts
43  8716  Applied    Aluminum
44  8807  Applied    Aluminum
45  8885  Applied    Aluminum
46  9000  Applied    Aluminum
47  9010  Applied    Aluminum
39  9010  Applied  Auto Parts
48  9013  Applied    Aluminum
40  9015  Applied  Auto Parts
49  9015  Applied    Aluminum
50  9020  Applied    Aluminum
41  9029  Applied  Auto Parts
51  9031  Applied    Aluminum
52  9040  Applied    Aluminum
53  9045  Applied    Aluminum
54  9060  Applied    Aluminum
55  9080  Applied    Aluminum
56  9081  Applied    Aluminum
57  9085  Applied    Aluminum
58  9090  Applied    Aluminum
59  9401  Applied    Aluminum
42  9401  Applied  Auto Parts
60  9403  Applied    Aluminum
52  9403  Applied       Steel
53  9405  Applied       Steel
61  9405  Applied    Aluminum
54  9406  Applied       Steel
62  9506  Applied    Aluminum
63  9507  Applied    Aluminum
64  9520  Applied    Aluminum
65  9596  Applied    Aluminum
66  9599  Applied    Aluminum
67  9603  Applied    Aluminum

In [22]:
AffectedHS.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\AffectedHS.csv")