In [1]:
import pandas as pd

In [2]:
TradeData_2023 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\TradeData_2023.csv")
TradeData_2023 = TradeData_2023[["refPeriodId","refYear","refMonth","flowCode","fobvalue"]]
TradeData_2023["fobvalue"] = TradeData_2023["fobvalue"]/1000000
TradeData_2024 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\TradeData_2024.csv")
TradeData_2024 = TradeData_2024[["refPeriodId","refYear","refMonth","flowCode","fobvalue"]]
TradeData_2024["fobvalue"] = TradeData_2024["fobvalue"]/1000000
TradeData_2025 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\TradeData_2025.csv")
TradeData_2025 = TradeData_2025[["refPeriodId","refYear","refMonth","flowCode","fobvalue"]]
TradeData_2025["fobvalue"] = TradeData_2025["fobvalue"]/1000000
TradeData = pd.concat([TradeData_2023,TradeData_2024,TradeData_2025])
TradeData

    refPeriodId  refYear  refMonth flowCode       fobvalue
C          2023        1    202301   Import  262545.905373
C          2023        1    202301   Export  165367.392270
C          2023        2    202302   Import  237813.657846
C          2023        2    202302   Export  158903.625574
C          2023        3    202303   Import  270111.501582
..          ...      ...       ...      ...            ...
C          2025        8    202508   Export  179619.870132
C          2025        9    202509   Import  282876.598589
C          2025        9    202509   Export  185451.810509
C          2025       10    202510   Import  281208.801955
C          2025       10    202510   Export  202576.702760

[68 rows x 5 columns]

In [50]:
TradeData2 = TradeData.pivot_table(index=["refPeriodId","refYear","refMonth"], columns="flowCode", values="fobvalue", aggfunc="sum").reset_index()
TradeData2["Balance"] = TradeData2["Export"] - TradeData2["Import"]
TradeData2.head()

flowCode,refPeriodId,refYear,refMonth,Export,Import,Balance
0,2023,1,202301,165367.392270,262545.905373,-97178.513103
1,2023,2,202302,158903.625574,237813.657846,-78910.032272
2,2023,3,202303,184407.050413,270111.501582,-85704.451169
3,2023,4,202304,162335.030837,257496.245015,-95161.214178
4,2023,5,202305,166622.285362,271281.227530,-104658.942168

In [ ]:
#TradeData2.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\ComBalance.csv")

In [57]:
IndProd = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\INDPRO_PC1.xlsx",sheet_name="Monthly")
IndProd.rename(columns={"INDPRO_PC1":"Ind_Prod"},inplace=True)
IndProd["YearMonth"] = IndProd["observation_date"].dt.strftime("%Y-%m")
IndProd.drop(columns="observation_date",inplace=True)
IndProd.head(5)

   Ind_Prod YearMonth
0   0.31881   2023-01
1  -0.16348   2023-02
2  -0.36512   2023-03
3  -0.18435   2023-04
4  -0.39957   2023-05

In [58]:
ImpPrice = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\IREXFDFLS_PC1.xlsx",sheet_name="Monthly")
ImpPrice.rename(columns={"IREXFDFLS_PC1":"Imp_Price"},inplace=True)
ImpPrice["YearMonth"] = ImpPrice["observation_date"].dt.strftime("%Y-%m")
ImpPrice.drop(columns="observation_date",inplace=True)
ImpPrice.head(5)

   Imp_Price YearMonth
0    0.55504   2023-01
1    0.00000   2023-02
2   -1.63043   2023-03
3   -1.89702   2023-04
4   -1.71946   2023-05

In [59]:
ProdPrice = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\PCUOMFGOMFG_PC1.xlsx",sheet_name="Monthly")
ProdPrice.rename(columns={"PCUOMFGOMFG_PC1":"Prod_Price"},inplace=True)
ProdPrice["YearMonth"] = ProdPrice["observation_date"].dt.strftime("%Y-%m")
ProdPrice.drop(columns="observation_date",inplace=True)
ProdPrice.head(5)

   Prod_Price YearMonth
0     7.63861   2023-01
1     5.08462   2023-02
2     1.45719   2023-03
3    -0.39149   2023-04
4    -3.97432   2023-05

In [60]:
ConsPrice = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\CPILFESL_PC1.xlsx",sheet_name="Monthly")
ConsPrice.rename(columns={"CPILFESL_PC1":"Cons_Price"},inplace=True)
ConsPrice["YearMonth"] = ConsPrice["observation_date"].dt.strftime("%Y-%m")
ConsPrice.drop(columns="observation_date",inplace=True)
ConsPrice.head(5)

   Cons_Price YearMonth
0     5.53953   2023-01
1     5.49826   2023-02
2     5.56674   2023-03
3     5.51436   2023-04
4     5.33755   2023-05

In [69]:
Customs = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\MTS v2.xlsx").drop(columns=["Unnamed: 0","Calendar Year","Calendar Month Number"])
Customs.rename(columns={"Current Month Receipt or Outlay Amount":"Customs Duties",
                        "Record Date":"observation_date"},inplace=True)
Customs["observation_date"] = pd.to_datetime(Customs["observation_date"])
Customs["YearMonth"] = Customs["observation_date"].dt.strftime("%Y-%m")
Customs.drop(columns="observation_date",inplace=True)
Customs.head()

   Customs Duties YearMonth
0    27892.382035   2025-12
1    30755.952020   2025-11
2    31353.501081   2025-10
3    29674.953322   2025-09
4    29502.942750   2025-08

In [79]:
Unemployment = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\UnempRate.xlsx")
Unemployment["observation_date"] = pd.to_datetime(Unemployment["observation_date"].astype(str),format="%Y-%d-%m")
Unemployment["YearMonth"] = Unemployment["observation_date"].dt.strftime("%Y-%m")
Unemployment.drop(columns="observation_date",inplace=True)
Unemployment.head()

   Unemployment rate YearMonth
0                3.5   2023-01
1                3.6   2023-02
2                3.5   2023-03
3                3.4   2023-04
4                3.6   2023-05

In [80]:
EmpManufacturing = pd.read_excel(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\Indexs\US indexs\EmpManuf.xlsx")
EmpManufacturing["YearMonth"] = EmpManufacturing["observation_date"].dt.strftime("%Y-%m")
EmpManufacturing.drop(columns="observation_date",inplace=True)
EmpManufacturing.head(5)

   EmpManuf YearMonth
0     12903   2023-01
1     12898   2023-02
2     12888   2023-03
3     12884   2023-04
4     12869   2023-05

In [81]:
TradeData3 = TradeData2[["refMonth","Balance"]]
TradeData3["observation_date"] = TradeData3["refMonth"].astype(str).str[0:4]+"-"+TradeData3["refMonth"].astype(str).str[-2:]+"-01"
TradeData3["observation_date"] = pd.to_datetime(TradeData3["observation_date"])
TradeData3.drop(columns="refMonth",inplace=True)
TradeData3["YearMonth"] = TradeData3["observation_date"].dt.strftime("%Y-%m")
TradeData3.drop(columns="observation_date",inplace=True)
TradeData3.head()

C:\Users\rcrds\AppData\Local\Temp\ipykernel_30844\755587125.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TradeData3["observation_date"] = TradeData3["refMonth"].astype(str).str[0:4]+"-"+TradeData3["refMonth"].astype(str).str[-2:]+"-01"
C:\Users\rcrds\AppData\Local\Temp\ipykernel_30844\755587125.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TradeData3["observation_date"] = pd.to_datetime(TradeData3["observation_date"])
C:\Users\rcrds\AppData\Local\Temp\ipykernel_30844\755587125.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TradeData3.drop(columns="refMonth",inplace=True)
C:\Users\rcrds\AppData\Local\Temp\ipykernel_30844\755587125.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TradeData3["YearMonth"] = TradeData3["observation_date"].dt.strftime("%Y-%m")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_30844\755587125.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TradeData3.drop(columns="observation_date",inplace=True)

flowCode        Balance YearMonth
0         -97178.513103   2023-01
1         -78910.032272   2023-02
2         -85704.451169   2023-03
3         -95161.214178   2023-04
4        -104658.942168   2023-05

In [83]:
US_ind1 = pd.merge(Unemployment,EmpManufacturing,how='left',on="YearMonth")
US_ind1.head()

   Unemployment rate YearMonth  EmpManuf
0                3.5   2023-01     12903
1                3.6   2023-02     12898
2                3.5   2023-03     12888
3                3.4   2023-04     12884
4                3.6   2023-05     12869

In [84]:
US_ind2 = pd.merge(TradeData3,Customs,how='left',on="YearMonth")
US_ind2.head()

         Balance YearMonth  Customs Duties
0  -97178.513103   2023-01     6837.686961
1  -78910.032272   2023-02     6349.062417
2  -85704.451169   2023-03     6151.606563
3  -95161.214178   2023-04     6349.693067
4 -104658.942168   2023-05     6373.091749

In [85]:
US_ind3 = pd.merge(ConsPrice,ProdPrice,how='left',on="YearMonth")
US_ind3.head()

   Cons_Price YearMonth  Prod_Price
0     5.53953   2023-01     7.63861
1     5.49826   2023-02     5.08462
2     5.56674   2023-03     1.45719
3     5.51436   2023-04    -0.39149
4     5.33755   2023-05    -3.97432

In [86]:
US_ind4 = pd.merge(ImpPrice,IndProd,how='left',on="YearMonth")
US_ind4.head()

   Imp_Price YearMonth  Ind_Prod
0    0.55504   2023-01   0.31881
1    0.00000   2023-02  -0.16348
2   -1.63043   2023-03  -0.36512
3   -1.89702   2023-04  -0.18435
4   -1.71946   2023-05  -0.39957

In [89]:
US_ind12 = pd.merge(US_ind1,US_ind2,how='left',on="YearMonth")
US_ind12.head()
US_ind34 = pd.merge(US_ind3,US_ind4,how='left',on="YearMonth")
US_ind34.head()
US_ind = pd.merge(US_ind12,US_ind34,how='left',on="YearMonth")
US_ind

,Unemployment rate,YearMonth,EmpManuf,Balance,Customs Duties,Cons_Price,Prod_Price,Imp_Price,Ind_Prod
0,3.5,2023-01,12903,-97178.513103,6837.686961,5.53953,7.63861,0.55504,0.31881
1,3.6,2023-02,12898,-78910.032272,6349.062417,5.49826,5.08462,0.00000,-0.16348
2,3.5,2023-03,12888,-85704.451169,6151.606563,5.56674,1.45719,-1.63043,-0.36512
3,3.4,2023-04,12884,-95161.214178,6349.693067,5.51436,-0.39149,-1.89702,-0.18435
4,3.6,2023-05,12869,-104658.942168,6373.091749,5.33755,-3.97432,-1.71946,-0.39957
5,3.6,2023-06,12875,-97827.017953,6475.488283,4.85360,-6.33874,-1.45719,-0.88935
6,3.5,2023-07,12862,-102968.078826,6909.949194,4.70097,-4.32393,-1.18939,-0.31248
7,3.7,2023-08,12861,-101641.067132,6325.140881,4.39914,-0.15945,-1.37363,-0.25421
8,3.7,2023-09,12872,-96910.141229,6678.440109,4.12875,0.18937,-1.19485,-0.26725
9,3.9,2023-10,12837,-105878.893332,6902.737489,4.02740,-1.93324,-1.37868,-0.77430
10,3.7,2023-11,12859,-96648.766085,6296.206194,4.01798,-2.53376,-0.73937,-0.09044
11,3.8,2023-12,12872,-86441.419858,5744.452855,3.91547,-0.75434,-1.10497,0.83866
12,3.7,2024-01,12875,-100381.354816,6476.625976,3.85835,-2.05556,-0.55198,-1.27625
13,3.9,2024-02,12852,-81981.078831,6208.388231,3.76196,-0.40632,-0.73394,-0.35433
14,3.9,2024-03,12836,-86874.622816,6064.284894,3.81619,0.21528,-0.36832,-0.55731
15,3.9,2024-04,12833,-107067.857608,6366.508728,3.62603,1.12357,0.27624,-0.99711
16,3.9,2024-05,12825,-109629.911678,5224.661702,3.39442,1.03856,0.18416,-0.06500
17,4.1,2024-06,12814,-98406.749436,6323.344669,3.26542,0.78768,0.73937,0.77347
18,4.2,2024-07,12806,-127170.393973,7133.488191,3.23019,1.79804,0.92593,-0.92263
19,4.2,2024-08,12772,-105153.596563,7046.951549,3.28510,-0.76665,1.20706,-0.40500
20,4.1,2024-09,12758,-122844.380214,7249.259468,3.28236,-2.38897,1.67442,-1.20044
21,4.1,2024-10,12697,-119881.699835,7297.256976,3.29869,-0.76389,2.14352,-0.99474
22,4.2,2024-11,12711,-107345.855383,6711.869038,3.28594,0.05639,1.95531,-1.55794
23,4.1,2024-12,12693,-126272.389054,6814.380564,3.21333,1.15799,1.76909,-0.27415
24,4.0,2025-01,12673,-161234.218625,7341.415937,3.28297,1.88727,1.11008,0.84900
25,4.2,2025-02,12671,-127672.143160,7246.812675,3.13756,0.81153,1.10906,0.81199
26,4.2,2025-03,12666,-159582.164919,8167.908460,2.80878,0.08496,1.01664,0.58025
27,4.2,2025-04,12662,-95029.716013,15633.917349,2.77602,-0.36241,0.73462,0.88235
28,4.3,2025-05,12651,-100758.634009,22172.564539,2.76584,1.04155,0.82721,0.10162
29,4.1,2025-06,12636,-92800.647696,26631.664232,2.91090,1.73381,0.45872,0.57932
30,4.3,2025-07,12625,-125395.077491,27670.054031,3.05449,1.52013,0.55046,1.91877
31,4.3,2025-08,12615,-90654.028801,29502.942750,3.11181,1.81645,0.73394,1.18868
32,4.4,2025-09,12612,-97424.788080,29674.953322,3.01997,3.36325,0.45746,1.90114
33,NaN,2025-10,12603,-78632.099195,31353.501081,NaN,2.50348,NaN,1.79703
34,4.5,2025-11,12593,NaN,NaN,2.59904,3.17310,0.82192,2.09986
35,4.4,2025-12,12585,NaN,NaN,2.64648,2.32848,1.18939,1.29805

In [90]:
US_ind.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\US Indexs.csv")