In [122]:
def four_digit(row):
    if len(row["HS4"])<4:
        return "0"+row["HS4"]
    else:
        return row["HS4"]

In [123]:
import pandas as pd

In [124]:

ex_df20 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2020_exports.csv", encoding="latin1")
ex_df21 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2021_exports.csv", encoding="latin1")
ex_df22 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2022_exports.csv", encoding="latin1")
ex_df23 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2023_exports.csv", encoding="latin1")
ex_df24 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2024_exports.csv", encoding="latin1")
#ex_df25 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months no Com\2025_exports.csv", encoding="latin1")

In [125]:
ex_df20

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0,128979511214,128979511214,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0,57945362,57945362,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0,3751018,3751018,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0,73749612,73749612,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0,392320,392320,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20201201,2020,12,202012,842,USA,USA,X,Export,...,True,0,False,0,16459235,16459235,4,False,True,NaN
C,M,20201201,2020,12,202012,842,USA,USA,X,Export,...,True,0,False,0,133093358,133093358,4,False,True,NaN
C,M,20201201,2020,12,202012,842,USA,USA,X,Export,...,True,0,False,0,1403493,1403493,4,False,True,NaN
C,M,20201201,2020,12,202012,842,USA,USA,X,Export,...,True,0,False,0,51285744,51285744,4,False,True,NaN
C,M,20201201,2020,12,202012,842,USA,USA,X,Export,...,True,0,False,0,12104521,12104521,4,False,True,NaN

In [126]:
ex_df21

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20210101,2021,1,202101,842,USA,USA,X,Export,...,True,0,False,NaN,127476378280,127476378280,4,False,True,NaN
C,M,20210101,2021,1,202101,842,USA,USA,X,Export,...,True,0,False,NaN,15449066,15449066,4,False,True,NaN
C,M,20210101,2021,1,202101,842,USA,USA,X,Export,...,True,0,False,NaN,5010612,5010612,4,False,True,NaN
C,M,20210101,2021,1,202101,842,USA,USA,X,Export,...,True,0,False,NaN,95459006,95459006,4,False,True,NaN
C,M,20210101,2021,1,202101,842,USA,USA,X,Export,...,True,0,False,NaN,170371,170371,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20211201,2021,12,202112,842,USA,USA,X,Export,...,True,0,False,0.0,16445094,16445094,4,False,True,NaN
C,M,20211201,2021,12,202112,842,USA,USA,X,Export,...,True,0,False,0.0,132630782,132630782,4,False,True,NaN
C,M,20211201,2021,12,202112,842,USA,USA,X,Export,...,True,0,False,0.0,1899765,1899765,4,False,True,NaN
C,M,20211201,2021,12,202112,842,USA,USA,X,Export,...,True,0,False,0.0,6502208,6502208,4,False,True,NaN
C,M,20211201,2021,12,202112,842,USA,USA,X,Export,...,True,0,False,0.0,11893863,11893863,4,False,True,NaN

In [127]:
ex_df22

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20220101,2022,1,202201,842,USA,USA,X,Export,...,True,0,False,0.0,147237687097,147237687097,4,False,True,NaN
C,M,20220101,2022,1,202201,842,USA,USA,X,Export,...,True,0,False,0.0,6994767,6994767,4,False,True,NaN
C,M,20220101,2022,1,202201,842,USA,USA,X,Export,...,True,0,False,0.0,3933670,3933670,4,False,True,NaN
C,M,20220101,2022,1,202201,842,USA,USA,X,Export,...,True,0,False,0.0,198554217,198554217,4,False,True,NaN
C,M,20220101,2022,1,202201,842,USA,USA,X,Export,...,True,0,False,0.0,452984,452984,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20221201,2022,12,202212,842,USA,USA,X,Export,...,True,0,False,0.0,278499742,278499742,4,False,True,NaN
C,M,20221201,2022,12,202212,842,USA,USA,X,Export,...,False,0,False,0.0,2864,2864,0,False,True,NaN
C,M,20221201,2022,12,202212,842,USA,USA,X,Export,...,True,0,False,0.0,1307052,1307052,4,False,True,NaN
C,M,20221201,2022,12,202212,842,USA,USA,X,Export,...,True,0,False,0.0,26137602,26137602,4,False,True,NaN
C,M,20221201,2022,12,202212,842,USA,USA,X,Export,...,True,0,False,0.0,7508083,7508083,4,False,True,NaN

In [128]:
ex_df23

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20230101,2023,1,202301,842,USA,USA,X,Export,...,True,0,False,NaN,165367392270,165367392270,4,False,True,NaN
C,M,20230101,2023,1,202301,842,USA,USA,X,Export,...,True,0,False,NaN,1913016,1913016,4,False,True,NaN
C,M,20230101,2023,1,202301,842,USA,USA,X,Export,...,True,0,False,NaN,12407972,12407972,4,False,True,NaN
C,M,20230101,2023,1,202301,842,USA,USA,X,Export,...,True,0,False,NaN,131556890,131556890,4,False,True,NaN
C,M,20230101,2023,1,202301,842,USA,USA,X,Export,...,True,0,False,NaN,412624,412624,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20231201,2023,12,202312,842,USA,USA,X,Export,...,True,0,False,NaN,51400497,51400497,4,False,True,NaN
C,M,20231201,2023,12,202312,842,USA,USA,X,Export,...,True,0,False,NaN,309862834,309862834,4,False,True,NaN
C,M,20231201,2023,12,202312,842,USA,USA,X,Export,...,True,0,False,NaN,2867254,2867254,4,False,True,NaN
C,M,20231201,2023,12,202312,842,USA,USA,X,Export,...,True,0,False,NaN,4783714,4783714,4,False,True,NaN
C,M,20231201,2023,12,202312,842,USA,USA,X,Export,...,True,0,False,NaN,5348068,5348068,4,False,True,NaN

In [129]:
ex_df24

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20240101,2024,1,202401,842,USA,USA,X,Export,...,True,0,False,NaN,160498257063,160498257063,4,False,True,NaN
C,M,20240101,2024,1,202401,842,USA,USA,X,Export,...,True,0,False,NaN,1998202,1998202,4,False,True,NaN
C,M,20240101,2024,1,202401,842,USA,USA,X,Export,...,True,0,False,NaN,8318229,8318229,4,False,True,NaN
C,M,20240101,2024,1,202401,842,USA,USA,X,Export,...,True,0,False,NaN,44788851,44788851,4,False,True,NaN
C,M,20240101,2024,1,202401,842,USA,USA,X,Export,...,True,0,False,NaN,290743,290743,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,60876297,60876297,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,401194965,401194965,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,3726531,3726531,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,22910053,22910053,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,8456366,8456366,4,False,True,NaN

In [130]:
exports_2020_2024 = pd.concat([ex_df20,ex_df21,ex_df22,ex_df23,ex_df24])

In [131]:
exports_2020_2024

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0.0,128979511214,128979511214,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0.0,57945362,57945362,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0.0,3751018,3751018,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0.0,73749612,73749612,4,False,True,NaN
C,M,20200101,2020,1,202001,842,USA,USA,X,Export,...,True,0,False,0.0,392320,392320,4,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,60876297,60876297,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,401194965,401194965,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,3726531,3726531,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,22910053,22910053,4,False,True,NaN
C,M,20241201,2024,12,202412,842,USA,USA,X,Export,...,True,0,False,NaN,8456366,8456366,4,False,True,NaN

In [132]:
col_drop = ["typeCode","period","reporterISO","reporterDesc","isGrossWgtEstimated","grossWgt","isNetWgtEstimated","netWgt","flowDesc","partnerCode","partnerDesc","altQtyUnitCode","isAggregate","partner2Code","partner2Desc","isAltQtyEstimated","partner2ISO","qty","legacyEstimationFlag","isReported","classificationSearchCode","motCode","classificationCode","mosCode","cmdDesc","aggrLevel","isLeaf","altQty","altQtyUnitAbbr","customsCode","qtyUnitCode","qtyUnitAbbr","customsDesc","motDesc","isQtyEstimated"]

In [133]:
exports_2020_2024.drop(columns=col_drop, inplace=True)
exports_2020_2024 = exports_2020_2024[exports_2020_2024["partnerISO"]!="World"]

In [134]:
exports_2020_2025

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerISO,HS4,HS4 Description,cifvalue,fobvalue,primaryValue
C,20200101,2020,1,202001,USA,Export,World,TOTAL,All Commodities,128979511214,128979511214,4
C,20200101,2020,1,202001,USA,Export,Afghanistan,TOTAL,All Commodities,57945362,57945362,4
C,20200101,2020,1,202001,USA,Export,Albania,TOTAL,All Commodities,3751018,3751018,4
C,20200101,2020,1,202001,USA,Export,Algeria,TOTAL,All Commodities,73749612,73749612,4
C,20200101,2020,1,202001,USA,Export,Andorra,TOTAL,All Commodities,392320,392320,4
...,...,...,...,...,...,...,...,...,...,...,...,...
C,20241201,2024,12,202412,USA,Export,Uzbekistan,TOTAL,All Commodities,60876297,60876297,4
C,20241201,2024,12,202412,USA,Export,Venezuela,TOTAL,All Commodities,401194965,401194965,4
C,20241201,2024,12,202412,USA,Export,Samoa,TOTAL,All Commodities,3726531,3726531,4
C,20241201,2024,12,202412,USA,Export,Yemen,TOTAL,All Commodities,22910053,22910053,4
C,20241201,2024,12,202412,USA,Export,Zambia,TOTAL,All Commodities,8456366,8456366,4

In [135]:
exports_2020_2024 = exports_2020_2024.rename(columns = {'freqCode':'YearMonthDay',
                                    "refPeriodId":"Year",
                                    "refYear":"Month",
                                    "refMonth":"YearMonth",
                                    "isOriginalClassification":"HS4",
                                    "cmdCode":"HS4 Description"})

In [136]:
exports_2020_2024["HS4"]=exports_2020_2024["HS4"].astype("string")

In [137]:
exports_2020_2024

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerISO,HS4,HS4 Description,cifvalue,fobvalue,primaryValue
C,20200101,2020,1,202001,USA,Export,Afghanistan,TOTAL,All Commodities,57945362,57945362,4
C,20200101,2020,1,202001,USA,Export,Albania,TOTAL,All Commodities,3751018,3751018,4
C,20200101,2020,1,202001,USA,Export,Algeria,TOTAL,All Commodities,73749612,73749612,4
C,20200101,2020,1,202001,USA,Export,Andorra,TOTAL,All Commodities,392320,392320,4
C,20200101,2020,1,202001,USA,Export,Angola,TOTAL,All Commodities,35210668,35210668,4
...,...,...,...,...,...,...,...,...,...,...,...,...
C,20241201,2024,12,202412,USA,Export,Uzbekistan,TOTAL,All Commodities,60876297,60876297,4
C,20241201,2024,12,202412,USA,Export,Venezuela,TOTAL,All Commodities,401194965,401194965,4
C,20241201,2024,12,202412,USA,Export,Samoa,TOTAL,All Commodities,3726531,3726531,4
C,20241201,2024,12,202412,USA,Export,Yemen,TOTAL,All Commodities,22910053,22910053,4
C,20241201,2024,12,202412,USA,Export,Zambia,TOTAL,All Commodities,8456366,8456366,4

In [138]:
exports_2020_2024["HS4"] = exports_2020_2024.apply(four_digit, axis=1)

In [139]:
exports_2020_2024.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\Exports_2020_2025.csv")

In [140]:
imp_2020_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_01-02.csv", encoding="latin1")
imp_2020_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_03-04.csv", encoding="latin1")
imp_2020_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_05-06.csv", encoding="latin1")
imp_2020_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_07-08.csv", encoding="latin1")
imp_2020_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_09-10.csv", encoding="latin1")
imp_2020_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_11-12.csv", encoding="latin1")

imp_2021_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_01-02.csv", encoding="latin1")
imp_2021_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_03-04.csv", encoding="latin1")
imp_2021_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_05-06.csv", encoding="latin1")
imp_2021_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_07-08.csv", encoding="latin1")
imp_2021_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_09-10.csv", encoding="latin1")
imp_2021_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_11-12.csv", encoding="latin1")

imp_2022_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_01-02.csv", encoding="latin1")
imp_2022_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_03-04.csv", encoding="latin1")
imp_2022_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_05-06.csv", encoding="latin1")
imp_2022_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_07-08.csv", encoding="latin1")
imp_2022_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_09-10.csv", encoding="latin1")
imp_2022_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_11-12.csv", encoding="latin1")

imp_2023_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_01-02.csv", encoding="latin1")
imp_2023_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_03-04.csv", encoding="latin1")
imp_2023_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_05-06.csv", encoding="latin1")
imp_2023_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_07-08.csv", encoding="latin1")
imp_2023_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_09-10.csv", encoding="latin1")
imp_2023_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_11-12.csv", encoding="latin1")

imp_2024_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_01-02.csv", encoding="latin1")
imp_2024_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_03-04.csv", encoding="latin1")
imp_2024_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_05-06.csv", encoding="latin1")
imp_2024_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_07-08.csv", encoding="latin1")
imp_2024_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_09-10.csv", encoding="latin1")
imp_2024_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_11-12.csv", encoding="latin1")

imp_2025_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_01-02.csv", encoding="latin1")
imp_2025_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_03-04.csv", encoding="latin1")
imp_2025_05 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_05-06.csv", encoding="latin1")
imp_2025_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_07-08.csv", encoding="latin1")
imp_2025_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_09-10.csv", encoding="latin1")

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:2: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2020_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2020_03-04.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:9: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2021_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_03-04.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:11: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2021_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2021_07-08.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:18: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2022_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_07-08.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:19: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2022_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_09-10.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:20: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2022_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2022_11-12.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:25: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2023_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_07-08.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:26: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2023_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_09-10.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:27: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2023_11 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2023_11-12.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:29: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2024_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_01-02.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:30: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2024_03 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2024_03-04.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:36: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2025_01 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_01-02.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:39: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2025_07 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_07-08.csv", encoding="latin1")
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1362181512.py:40: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  imp_2025_09 = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Original Datasets\2020-2024 months with Com\imp_2025_09-10.csv", encoding="latin1")

In [141]:
imports_2020_2025 = pd.concat([imp_2020_01,imp_2020_03,imp_2020_05,imp_2020_07,imp_2020_09,imp_2020_11,imp_2021_01,imp_2021_03,imp_2021_05,imp_2021_07,imp_2021_09,imp_2021_11,imp_2022_01,imp_2022_03,imp_2022_05,imp_2022_07,imp_2022_09,imp_2022_11,imp_2023_01,imp_2023_03,imp_2023_05,imp_2023_07,imp_2023_09,imp_2023_11,imp_2024_01,imp_2024_03,imp_2024_05,imp_2024_07,imp_2024_09,imp_2024_11,imp_2025_01,imp_2025_03,imp_2025_05,imp_2025_07,imp_2025_09])

In [142]:
col_drop2 = ["isLeaf","qty","classificationSearchCode","altQty","partner2Desc","classificationCode","aggrLevel","mosCode","customsCode","customsDesc","partner2Code","partner2ISO","motCode","motDesc","qtyUnitCode","typeCode","period","reporterISO","reporterDesc","netWgt","isNetWgtEstimated","grossWgt","isGrossWgtEstimated","legacyEstimationFlag","isReported","isAggregate","qtyUnitAbbr","flowDesc","partnerDesc","isQtyEstimated","altQtyUnitCode","altQtyUnitAbbr","isAltQtyEstimated"]

In [143]:
imports_2020_2025.drop(columns=col_drop2, inplace=True)

In [144]:
imports_2020_2025 = imports_2020_2025.rename(columns = {'freqCode':'YearMonthDay',
                                    "refPeriodId":"Year",
                                    "refYear":"Month",
                                    "refMonth":"YearMonth",
                                    "isOriginalClassification":"HS4",
                                    "cmdCode":"HS4 Description"})

In [145]:
imports_2020_2025

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,HS4 Description,cmdDesc,cifvalue,fobvalue,primaryValue
C,20200101,2020,1,202001,USA,Import,ARG,Argentina,5701,Carpets and other textile floor coverings; kno...,4,8.000000e+03,8650,4
C,20200101,2020,1,202001,USA,Import,FIN,Finland,5701,Carpets and other textile floor coverings; kno...,4,1.478000e+03,1511,4
C,20200101,2020,1,202001,USA,Import,ZAF,South Africa,5701,Carpets and other textile floor coverings; kno...,4,1.506300e+04,16337,4
C,20200101,2020,1,202001,USA,Import,ARM,Armenia,5701,Carpets and other textile floor coverings; kno...,4,4.334000e+03,4534,4
C,20200101,2020,1,202001,USA,Import,HUN,Hungary,5701,Carpets and other textile floor coverings; kno...,4,2.965500e+04,29656,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,20251001,2025,10,202510,USA,Import,W00,World,2834,Nitrites; nitrates,4,5.570235e+06,6362446,6
C,20251001,2025,10,202510,USA,Import,W00,World,2915,Acids; saturated acyclic monocarboxylic acids ...,4,6.124241e+07,65269213,6
C,20251001,2025,10,202510,USA,Import,W00,World,2929,"Nitrogen-function compounds, n.e.c. in chapter 29",4,1.693331e+07,17264066,6
C,20251001,2025,10,202510,USA,Import,W00,World,2930,Organo-sulphur compounds,4,5.858781e+07,60742964,6
C,20251001,2025,10,202510,USA,Import,W00,World,3004,"Medicaments; (not goods of heading no. 3002, 3...",4,6.100726e+09,6134696396,6

In [146]:
imports_2020_2025.cifvalue.fillna(0, inplace=True)

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\2707207642.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  imports_2020_2025.cifvalue.fillna(0, inplace=True)

In [147]:
imports_2020_2025.isnull().sum()

YearMonthDay       0
Year               0
Month              0
YearMonth          0
reporterCode       0
flowCode           0
partnerCode        0
partnerISO         0
HS4                0
HS4 Description    0
cmdDesc            0
cifvalue           0
fobvalue           0
primaryValue       0
dtype: int64

In [148]:
imports_2020_2025["cifvalue"]=imports_2020_2025["cifvalue"].astype("int")

In [149]:
imports_2020_2025["HS4"]=imports_2020_2025["HS4"].astype("string")

In [150]:
imports_2020_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2530488 entries, C to C
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   YearMonthDay     int64
 1   Year             int64
 2   Month            int64
 3   YearMonth        int64
 4   reporterCode     object
 5   flowCode         object
 6   partnerCode      object
 7   partnerISO       object
 8   HS4              string
 9   HS4 Description  object
 10  cmdDesc          int64
 11  cifvalue         int64
 12  fobvalue         int64
 13  primaryValue     int64
dtypes: int64(8), object(5), string(1)
memory usage: 289.6+ MB

In [151]:
imports_2020_2025

,YearMonthDay,Year,Month,YearMonth,reporterCode,flowCode,partnerCode,partnerISO,HS4,HS4 Description,cmdDesc,cifvalue,fobvalue,primaryValue
C,20200101,2020,1,202001,USA,Import,ARG,Argentina,5701,Carpets and other textile floor coverings; kno...,4,8000,8650,4
C,20200101,2020,1,202001,USA,Import,FIN,Finland,5701,Carpets and other textile floor coverings; kno...,4,1478,1511,4
C,20200101,2020,1,202001,USA,Import,ZAF,South Africa,5701,Carpets and other textile floor coverings; kno...,4,15063,16337,4
C,20200101,2020,1,202001,USA,Import,ARM,Armenia,5701,Carpets and other textile floor coverings; kno...,4,4334,4534,4
C,20200101,2020,1,202001,USA,Import,HUN,Hungary,5701,Carpets and other textile floor coverings; kno...,4,29655,29656,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,20251001,2025,10,202510,USA,Import,W00,World,2834,Nitrites; nitrates,4,5570235,6362446,6
C,20251001,2025,10,202510,USA,Import,W00,World,2915,Acids; saturated acyclic monocarboxylic acids ...,4,61242408,65269213,6
C,20251001,2025,10,202510,USA,Import,W00,World,2929,"Nitrogen-function compounds, n.e.c. in chapter 29",4,16933307,17264066,6
C,20251001,2025,10,202510,USA,Import,W00,World,2930,Organo-sulphur compounds,4,58587806,60742964,6
C,20251001,2025,10,202510,USA,Import,W00,World,3004,"Medicaments; (not goods of heading no. 3002, 3...",4,6100725502,6134696396,6

In [152]:
imports_2020_2025["HS4"] = imports_2020_2025.apply(four_digit, axis=1)

In [153]:
#imports_2020_2025.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\Imports_2020_2025.csv")

In [154]:
HS_codes = imports_2020_2025[["HS4","HS4 Description"]]
HS_codes.drop_duplicates(inplace=True)
HS_codes

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1075425935.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HS_codes.drop_duplicates(inplace=True)

     HS4                                    HS4 Description
C   5701  Carpets and other textile floor coverings; kno...
C   5702  Carpets and other textile floor coverings; wov...
C   5703  Carpets and other textile floor coverings; tuf...
C   5704  Carpets and other textile floor coverings; of ...
C   5705  Carpets and other textile floor coverings; n.e...
..   ...                                                ...
C   0410  Animal products; insects and other edible prod...
C   3827  Mixtures containing halogenated derivatives of...
C   8806                                  Unmanned aircraft
C   2404  Products containing tobacco, reconstituted tob...
C   1203                                              Copra

[1288 rows x 2 columns]

In [155]:
HS_codes[HS_codes["HS4"].str.len()<4]

Empty DataFrame
Columns: [HS4, HS4 Description]
Index: []

In [156]:
HS_codes["HS4"] = HS_codes.apply(four_digit, axis=1)
HS_codes

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\911997458.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HS_codes["HS4"] = HS_codes.apply(four_digit, axis=1)

     HS4                                    HS4 Description
C   5701  Carpets and other textile floor coverings; kno...
C   5702  Carpets and other textile floor coverings; wov...
C   5703  Carpets and other textile floor coverings; tuf...
C   5704  Carpets and other textile floor coverings; of ...
C   5705  Carpets and other textile floor coverings; n.e...
..   ...                                                ...
C   0410  Animal products; insects and other edible prod...
C   3827  Mixtures containing halogenated derivatives of...
C   8806                                  Unmanned aircraft
C   2404  Products containing tobacco, reconstituted tob...
C   1203                                              Copra

[1288 rows x 2 columns]

In [157]:
HS_codes["HS2"] = HS_codes["HS4"].str[0:2]
HS_codes

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\2340608864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HS_codes["HS2"] = HS_codes["HS4"].str[0:2]

     HS4                                    HS4 Description HS2
C   5701  Carpets and other textile floor coverings; kno...  57
C   5702  Carpets and other textile floor coverings; wov...  57
C   5703  Carpets and other textile floor coverings; tuf...  57
C   5704  Carpets and other textile floor coverings; of ...  57
C   5705  Carpets and other textile floor coverings; n.e...  57
..   ...                                                ...  ..
C   0410  Animal products; insects and other edible prod...  04
C   3827  Mixtures containing halogenated derivatives of...  38
C   8806                                  Unmanned aircraft  88
C   2404  Products containing tobacco, reconstituted tob...  24
C   1203                                              Copra  12

[1288 rows x 3 columns]

In [158]:
chap = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\Chapters.csv", dtype={"InitRange": str,
                                                                                                        "FinalRange": str})

In [159]:
chap.drop(columns="Unnamed: 0")

,Section No.,Chapter Range,Section Title,Example,InitRange,FinalRange
0,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",01,05
1,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",06,14
2,III,15,Animal or Vegetable Fats and Oils,"Soybean oil, butter, margarine",15,15
3,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",16,24
4,V,25 - 27,Mineral Products,"Salt, coal, crude oil",25,27
5,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",28,38
6,VII,39 - 40,Plastics and Rubber,"Plastic packaging, rubber tyres",39,40
7,VIII,41 - 43,"Raw Hides, Skins, Leather, and Furskins","Leather hides, fur skins",41,43
8,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",44,46
9,X,47 - 49,Pulp of Wood; Paper; Printing Industry Products,"Newsprint, books, cartons",47,49
10,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",50,63
11,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",64,67
12,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",68,70
13,XIV,71,"Pearls, Precious Stones and Metals","Gold, diamonds, jewelry",71,71
14,XV,72 - 83,Base Metals and Articles of Base Metal,"Iron rods, copper wires, tools",72,83
15,XVI,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",84,85
16,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",86,89
17,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",90,92
18,XIX,93,Arms and Ammunition,"Rifles, pistols, military equipment",93,93
19,XX,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",94,96
20,XXI,97 - 99,"Works of Art, Collectors’ Pieces, and Special ...","Paintings, antiques, special codes",97,99

In [160]:
def aloc_section(df1,df2):
    result = []

    for hs in df1["HS2"].astype(int):
        match = df2[(df2["InitRange"].astype(int) <= hs) &(df2["FinalRange"].astype(int) >= hs)]
        if len(match) > 0:
            result.append(match.iloc[0]["Section No."])
        else:
            result.append(None)
    return result
        
HS_codes["Section"] = aloc_section(HS_codes,chap)
HS_codes

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\2262333971.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HS_codes["Section"] = aloc_section(HS_codes,chap)

     HS4                                    HS4 Description HS2 Section
C   5701  Carpets and other textile floor coverings; kno...  57      XI
C   5702  Carpets and other textile floor coverings; wov...  57      XI
C   5703  Carpets and other textile floor coverings; tuf...  57      XI
C   5704  Carpets and other textile floor coverings; of ...  57      XI
C   5705  Carpets and other textile floor coverings; n.e...  57      XI
..   ...                                                ...  ..     ...
C   0410  Animal products; insects and other edible prod...  04       I
C   3827  Mixtures containing halogenated derivatives of...  38      VI
C   8806                                  Unmanned aircraft  88    XVII
C   2404  Products containing tobacco, reconstituted tob...  24      IV
C   1203                                              Copra  12      II

[1288 rows x 4 columns]

In [161]:
HS_codes[["HS4","HS4 Description"]]

     HS4                                    HS4 Description
C   5701  Carpets and other textile floor coverings; kno...
C   5702  Carpets and other textile floor coverings; wov...
C   5703  Carpets and other textile floor coverings; tuf...
C   5704  Carpets and other textile floor coverings; of ...
C   5705  Carpets and other textile floor coverings; n.e...
..   ...                                                ...
C   0410  Animal products; insects and other edible prod...
C   3827  Mixtures containing halogenated derivatives of...
C   8806                                  Unmanned aircraft
C   2404  Products containing tobacco, reconstituted tob...
C   1203                                              Copra

[1288 rows x 2 columns]

In [162]:
HS_codes_2 = pd.merge(HS_codes,chap,how="left",left_on="Section",right_on="Section No.")

In [163]:
HS_codes_2.drop(columns=["Unnamed: 0","InitRange","FinalRange","Section No."],inplace=True)

In [164]:
HS_codes_2

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example
0,5701,Carpets and other textile floor coverings; kno...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
1,5702,Carpets and other textile floor coverings; wov...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
2,5703,Carpets and other textile floor coverings; tuf...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
3,5704,Carpets and other textile floor coverings; of ...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
4,5705,Carpets and other textile floor coverings; n.e...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
...,...,...,...,...,...,...,...
1283,0410,Animal products; insects and other edible prod...,04,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs"
1284,3827,Mixtures containing halogenated derivatives of...,38,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes"
1285,8806,Unmanned aircraft,88,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships"
1286,2404,"Products containing tobacco, reconstituted tob...",24,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco"
1287,1203,Copra,12,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals"

In [165]:
affected = pd.read_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\AffectedHS.csv", dtype={"HS4": str}).drop(columns="Unnamed: 0")
affected

      HS4   Tariff       Scope
0    4009  Applied  Auto Parts
1    4011  Applied  Auto Parts
2    4012  Applied  Auto Parts
3    4013  Applied  Auto Parts
4    4016  Applied  Auto Parts
..    ...      ...         ...
163  9507  Applied    Aluminum
164  9520  Applied    Aluminum
165  9596  Applied    Aluminum
166  9599  Applied    Aluminum
167  9603  Applied    Aluminum

[168 rows x 3 columns]

In [166]:
HS_codes_3 = pd.merge(HS_codes_2,affected,how="left",on="HS4")
HS_codes_3

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example,Tariff,Scope
0,5701,Carpets and other textile floor coverings; kno...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",NaN,NaN
1,5702,Carpets and other textile floor coverings; wov...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",NaN,NaN
2,5703,Carpets and other textile floor coverings; tuf...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",NaN,NaN
3,5704,Carpets and other textile floor coverings; of ...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",NaN,NaN
4,5705,Carpets and other textile floor coverings; n.e...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",NaN,NaN
...,...,...,...,...,...,...,...,...,...
1299,0410,Animal products; insects and other edible prod...,04,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",NaN,NaN
1300,3827,Mixtures containing halogenated derivatives of...,38,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",NaN,NaN
1301,8806,Unmanned aircraft,88,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",NaN,NaN
1302,2404,"Products containing tobacco, reconstituted tob...",24,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",NaN,NaN
1303,1203,Copra,12,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",NaN,NaN

In [167]:
HS_codes_3.Tariff.fillna("Not Applied", inplace=True)
HS_codes_3.Scope.fillna("Not Applicable", inplace=True)

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\246838062.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  HS_codes_3.Tariff.fillna("Not Applied", inplace=True)
C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\246838062.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  HS_codes_3.Scope.fillna("Not Applicable", inplace=True)

In [169]:
HS_codes_3.drop(columns=["Scope"], inplace=True)
HS_codes_3 = HS_codes_3.drop_duplicates(subset=['HS4'], keep='first')
HS_codes_3

,HS4,HS4 Description,HS2,Section,Chapter Range,Section Title,Example,Tariff
0,5701,Carpets and other textile floor coverings; kno...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
1,5702,Carpets and other textile floor coverings; wov...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
2,5703,Carpets and other textile floor coverings; tuf...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
3,5704,Carpets and other textile floor coverings; of ...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
4,5705,Carpets and other textile floor coverings; n.e...,57,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",Not Applied
...,...,...,...,...,...,...,...,...
1298,0309,"Flours, meals and pellets of fish, crustaceans...",03,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",Not Applied
1300,3827,Mixtures containing halogenated derivatives of...,38,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",Not Applied
1301,8806,Unmanned aircraft,88,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",Not Applied
1302,2404,"Products containing tobacco, reconstituted tob...",24,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",Not Applied
1303,1203,Copra,12,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",Not Applied

In [175]:
HS_codes_3["Section Title"].unique()

array(['Textiles and Textile Articles',
       'Articles of Stone, Cement, Ceramic, and Glass',
       'Chemicals and Allied Industries', 'Footwear, Headgear, Umbrellas',
       'Wood and Articles of Wood', 'Mineral Products',
       'Miscellaneous Manufactured Articles',
       'Optical, Precision, Medical Instruments', 'Plastics and Rubber',
       'Machinery and Electrical Equipment',
       'Live Animals; Animal Products', 'Vegetable Products',
       'Works of Art, Collectors’ Pieces, and Special Transactions',
       'Vehicles, Aircraft, and Vessels', 'Arms and Ammunition',
       'Raw Hides, Skins, Leather, and Furskins',
       'Base Metals and Articles of Base Metal',
       'Pulp of Wood; Paper; Printing Industry Products',
       'Pearls, Precious Stones and Metals',
       'Prepared Foodstuffs; Beverages; Tobacco',
       'Animal or Vegetable Fats and Oils'], dtype=object)

In [171]:
HS_codes_3.drop_duplicates(inplace=True)

C:\Users\rcrds\AppData\Local\Temp\ipykernel_2356\1554790307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HS_codes_3.drop_duplicates(inplace=True)

In [172]:
HS_codes_3.HS4.value_counts()

HS4
5701    1
5702    1
5703    1
5704    1
5705    1
       ..
0309    1
3827    1
8806    1
2404    1
1203    1
Name: count, Length: 1231, dtype: int64

In [174]:
HS_codes_3.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\HS_codes_improved.csv")