In [40]:
import pandas as pd

import requests
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36"
}

url = "https://exporterai.com/chapters.html"
response = requests.get(url, headers=headers)
response

In [41]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.content, "html.parser")

In [42]:
section = soup.find('section', id='chapter-table')
table = section.find('table', class_='table custom-table')
table

<table class="table custom-table">
<thead>
<tr>
<th>Section No.</th>
<th>Chapter Range</th>
<th>Section Title</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr>
<td>I</td>
<td>01 - 05</td>
<td>Live Animals; Animal Products</td>
<td>Cattle, fish, dairy, eggs</td>
</tr>
<tr>
<td>II</td>
<td>06 - 14</td>
<td>Vegetable Products</td>
<td>Fruits, vegetables, coffee, cereals</td>
</tr>
<tr>
<td>III</td>
<td>15</td>
<td>Animal or Vegetable Fats and Oils</td>
<td>Soybean oil, butter, margarine</td>
</tr>
<tr>
<td>IV</td>
<td>16 - 24</td>
<td>Prepared Foodstuffs; Beverages; Tobacco</td>
<td>Soft drinks, biscuits, tobacco</td>
</tr>
<tr>
<td>V</td>
<td>25 - 27</td>
<td>Mineral Products</td>
<td>Salt, coal, crude oil</td>
</tr>
<tr>
<td>VI</td>
<td>28 - 38</td>
<td>Chemicals and Allied Industries</td>
<td>Fertilizers, paints, perfumes</td>
</tr>
<tr>
<td>VII</td>
<td>39 - 40</td>
<td>Plastics and Rubber</td>
<td>Plastic packaging, rubber tyres</td>
</tr>
<tr>
<td>VIII</td>
<td>41 - 43</td>
<td>Raw Hides, Skins, Leather, and Furskins</td>
<td>Leather hides, fur skins</td>
</tr>
<tr>
<td>IX</td>
<td>44 - 46</td>
<td>Wood and Articles of Wood</td>
<td>Plywood, wooden furniture</td>
</tr>
<tr>
<td>X</td>
<td>47 - 49</td>
<td>Pulp of Wood; Paper; Printing Industry Products</td>
<td>Newsprint, books, cartons</td>
</tr>
<tr>
<td>XI</td>
<td>50 - 63</td>
<td>Textiles and Textile Articles</td>
<td>Garments, fabrics, carpets</td>
</tr>
<tr>
<td>XII</td>
<td>64 - 67</td>
<td>Footwear, Headgear, Umbrellas</td>
<td>Shoes, helmets, umbrellas</td>
</tr>
<tr>
<td>XIII</td>
<td>68 - 70</td>
<td>Articles of Stone, Cement, Ceramic, and Glass</td>
<td>Tiles, ceramic ware, glassware</td>
</tr>
<tr>
<td>XIV</td>
<td>71</td>
<td>Pearls, Precious Stones and Metals</td>
<td>Gold, diamonds, jewelry</td>
</tr>
<tr>
<td>XV</td>
<td>72 - 83</td>
<td>Base Metals and Articles of Base Metal</td>
<td>Iron rods, copper wires, tools</td>
</tr>
<tr>
<td>XVI</td>
<td>84 - 85</td>
<td>Machinery and Electrical Equipment</td>
<td>Laptops, motors, washing machines</td>
</tr>
<tr>
<td>XVII</td>
<td>86 - 89</td>
<td>Vehicles, Aircraft, and Vessels</td>
<td>Cars, airplanes, ships</td>
</tr>
<tr>
<td>XVIII</td>
<td>90 - 92</td>
<td>Optical, Precision, Medical Instruments</td>
<td>Cameras, microscopes, X-ray machines</td>
</tr>
<tr>
<td>XIX</td>
<td>93</td>
<td>Arms and Ammunition</td>
<td>Rifles, pistols, military equipment</td>
</tr>
<tr>
<td>XX</td>
<td>94 - 96</td>
<td>Miscellaneous Manufactured Articles</td>
<td>Toys, furniture, kitchenware</td>
</tr>
<tr>
<td>XXI</td>
<td>97 - 99</td>
<td>Works of Art, Collectors’ Pieces, and Special Transactions</td>
<td>Paintings, antiques, special codes</td>
</tr>
</tbody>
</table>

In [43]:
rows = table.find_all('tr')
rows

[<tr>
 <th>Section No.</th>
 <th>Chapter Range</th>
 <th>Section Title</th>
 <th>Example</th>
 </tr>,
 <tr>
 <td>I</td>
 <td>01 - 05</td>
 <td>Live Animals; Animal Products</td>
 <td>Cattle, fish, dairy, eggs</td>
 </tr>,
 <tr>
 <td>II</td>
 <td>06 - 14</td>
 <td>Vegetable Products</td>
 <td>Fruits, vegetables, coffee, cereals</td>
 </tr>,
 <tr>
 <td>III</td>
 <td>15</td>
 <td>Animal or Vegetable Fats and Oils</td>
 <td>Soybean oil, butter, margarine</td>
 </tr>,
 <tr>
 <td>IV</td>
 <td>16 - 24</td>
 <td>Prepared Foodstuffs; Beverages; Tobacco</td>
 <td>Soft drinks, biscuits, tobacco</td>
 </tr>,
 <tr>
 <td>V</td>
 <td>25 - 27</td>
 <td>Mineral Products</td>
 <td>Salt, coal, crude oil</td>
 </tr>,
 <tr>
 <td>VI</td>
 <td>28 - 38</td>
 <td>Chemicals and Allied Industries</td>
 <td>Fertilizers, paints, perfumes</td>
 </tr>,
 <tr>
 <td>VII</td>
 <td>39 - 40</td>
 <td>Plastics and Rubber</td>
 <td>Plastic packaging, rubber tyres</td>
 </tr>,
 <tr>
 <td>VIII</td>
 <td>41 - 43</td>
 <td>Raw Hides, Skins, Leather, and Furskins</td>
 <td>Leather hides, fur skins</td>
 </tr>,
 <tr>
 <td>IX</td>
 <td>44 - 46</td>
 <td>Wood and Articles of Wood</td>
 <td>Plywood, wooden furniture</td>
 </tr>,
 <tr>
 <td>X</td>
 <td>47 - 49</td>
 <td>Pulp of Wood; Paper; Printing Industry Products</td>
 <td>Newsprint, books, cartons</td>
 </tr>,
 <tr>
 <td>XI</td>
 <td>50 - 63</td>
 <td>Textiles and Textile Articles</td>
 <td>Garments, fabrics, carpets</td>
 </tr>,
 <tr>
 <td>XII</td>
 <td>64 - 67</td>
 <td>Footwear, Headgear, Umbrellas</td>
 <td>Shoes, helmets, umbrellas</td>
 </tr>,
 <tr>
 <td>XIII</td>
 <td>68 - 70</td>
 <td>Articles of Stone, Cement, Ceramic, and Glass</td>
 <td>Tiles, ceramic ware, glassware</td>
 </tr>,
 <tr>
 <td>XIV</td>
 <td>71</td>
 <td>Pearls, Precious Stones and Metals</td>
 <td>Gold, diamonds, jewelry</td>
 </tr>,
 <tr>
 <td>XV</td>
 <td>72 - 83</td>
 <td>Base Metals and Articles of Base Metal</td>
 <td>Iron rods, copper wires, tools</td>
 </tr>,
 <tr>
 <td>XVI</td>
 <td>84 - 85</td>
 <td>Machinery and Electrical Equipment</td>
 <td>Laptops, motors, washing machines</td>
 </tr>,
 <tr>
 <td>XVII</td>
 <td>86 - 89</td>
 <td>Vehicles, Aircraft, and Vessels</td>
 <td>Cars, airplanes, ships</td>
 </tr>,
 <tr>
 <td>XVIII</td>
 <td>90 - 92</td>
 <td>Optical, Precision, Medical Instruments</td>
 <td>Cameras, microscopes, X-ray machines</td>
 </tr>,
 <tr>
 <td>XIX</td>
 <td>93</td>
 <td>Arms and Ammunition</td>
 <td>Rifles, pistols, military equipment</td>
 </tr>,
 <tr>
 <td>XX</td>
 <td>94 - 96</td>
 <td>Miscellaneous Manufactured Articles</td>
 <td>Toys, furniture, kitchenware</td>
 </tr>,
 <tr>
 <td>XXI</td>
 <td>97 - 99</td>
 <td>Works of Art, Collectors’ Pieces, and Special Transactions</td>
 <td>Paintings, antiques, special codes</td>
 </tr>]

In [44]:
heads = table.find_all("th")
columns = [th.get_text(strip=True) for th in heads]

chapters = pd.DataFrame(columns=columns)
chapters

Empty DataFrame
Columns: [Section No., Chapter Range, Section Title, Example]
Index: []

In [45]:
data = [
    [cell.get_text(strip=True) for cell in row.find_all(["td", "th"])]
    for row in table.find_all("tr")
]

chapters = pd.DataFrame(data[1:], columns=data[0])
chapters

,Section No.,Chapter Range,Section Title,Example
0,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs"
1,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals"
2,III,15,Animal or Vegetable Fats and Oils,"Soybean oil, butter, margarine"
3,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco"
4,V,25 - 27,Mineral Products,"Salt, coal, crude oil"
5,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes"
6,VII,39 - 40,Plastics and Rubber,"Plastic packaging, rubber tyres"
7,VIII,41 - 43,"Raw Hides, Skins, Leather, and Furskins","Leather hides, fur skins"
8,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture"
9,X,47 - 49,Pulp of Wood; Paper; Printing Industry Products,"Newsprint, books, cartons"
10,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets"
11,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas"
12,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware"
13,XIV,71,"Pearls, Precious Stones and Metals","Gold, diamonds, jewelry"
14,XV,72 - 83,Base Metals and Articles of Base Metal,"Iron rods, copper wires, tools"
15,XVI,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines"
16,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships"
17,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines"
18,XIX,93,Arms and Ammunition,"Rifles, pistols, military equipment"
19,XX,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware"
20,XXI,97 - 99,"Works of Art, Collectors’ Pieces, and Special ...","Paintings, antiques, special codes"

In [48]:
chapters["InitRange"] = chapters["Chapter Range"].str[0:2]
chapters

,Section No.,Chapter Range,Section Title,Example,InitRange
0,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",01
1,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",06
2,III,15,Animal or Vegetable Fats and Oils,"Soybean oil, butter, margarine",15
3,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",16
4,V,25 - 27,Mineral Products,"Salt, coal, crude oil",25
5,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",28
6,VII,39 - 40,Plastics and Rubber,"Plastic packaging, rubber tyres",39
7,VIII,41 - 43,"Raw Hides, Skins, Leather, and Furskins","Leather hides, fur skins",41
8,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",44
9,X,47 - 49,Pulp of Wood; Paper; Printing Industry Products,"Newsprint, books, cartons",47
10,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",50
11,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",64
12,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",68
13,XIV,71,"Pearls, Precious Stones and Metals","Gold, diamonds, jewelry",71
14,XV,72 - 83,Base Metals and Articles of Base Metal,"Iron rods, copper wires, tools",72
15,XVI,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",84
16,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",86
17,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",90
18,XIX,93,Arms and Ammunition,"Rifles, pistols, military equipment",93
19,XX,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",94
20,XXI,97 - 99,"Works of Art, Collectors’ Pieces, and Special ...","Paintings, antiques, special codes",97

In [50]:
chapters["FinalRange"] = chapters["Chapter Range"].str[-2:]
chapters

,Section No.,Chapter Range,Section Title,Example,InitRange,FinalRange
0,I,01 - 05,Live Animals; Animal Products,"Cattle, fish, dairy, eggs",01,05
1,II,06 - 14,Vegetable Products,"Fruits, vegetables, coffee, cereals",06,14
2,III,15,Animal or Vegetable Fats and Oils,"Soybean oil, butter, margarine",15,15
3,IV,16 - 24,Prepared Foodstuffs; Beverages; Tobacco,"Soft drinks, biscuits, tobacco",16,24
4,V,25 - 27,Mineral Products,"Salt, coal, crude oil",25,27
5,VI,28 - 38,Chemicals and Allied Industries,"Fertilizers, paints, perfumes",28,38
6,VII,39 - 40,Plastics and Rubber,"Plastic packaging, rubber tyres",39,40
7,VIII,41 - 43,"Raw Hides, Skins, Leather, and Furskins","Leather hides, fur skins",41,43
8,IX,44 - 46,Wood and Articles of Wood,"Plywood, wooden furniture",44,46
9,X,47 - 49,Pulp of Wood; Paper; Printing Industry Products,"Newsprint, books, cartons",47,49
10,XI,50 - 63,Textiles and Textile Articles,"Garments, fabrics, carpets",50,63
11,XII,64 - 67,"Footwear, Headgear, Umbrellas","Shoes, helmets, umbrellas",64,67
12,XIII,68 - 70,"Articles of Stone, Cement, Ceramic, and Glass","Tiles, ceramic ware, glassware",68,70
13,XIV,71,"Pearls, Precious Stones and Metals","Gold, diamonds, jewelry",71,71
14,XV,72 - 83,Base Metals and Articles of Base Metal,"Iron rods, copper wires, tools",72,83
15,XVI,84 - 85,Machinery and Electrical Equipment,"Laptops, motors, washing machines",84,85
16,XVII,86 - 89,"Vehicles, Aircraft, and Vessels","Cars, airplanes, ships",86,89
17,XVIII,90 - 92,"Optical, Precision, Medical Instruments","Cameras, microscopes, X-ray machines",90,92
18,XIX,93,Arms and Ammunition,"Rifles, pistols, military equipment",93,93
19,XX,94 - 96,Miscellaneous Manufactured Articles,"Toys, furniture, kitchenware",94,96
20,XXI,97 - 99,"Works of Art, Collectors’ Pieces, and Special ...","Paintings, antiques, special codes",97,99

In [52]:
chapters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Section No.    21 non-null     object
 1   Chapter Range  21 non-null     object
 2   Section Title  21 non-null     object
 3   Example        21 non-null     object
 4   InitRange      21 non-null     object
 5   FinalRange     21 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB

In [51]:
chapters.to_csv(r"C:\Users\rcrds\Desktop\Ironhack\Final Project\Clean Datasets\Chapters.csv")